export const polymers = [
  {
    id: 1,
    title: "Ethylene Vinyl Acetate (EVA)",
    img: "./assets/images/Products-all-img/chemicals/polymers/polymer-1.webp",
    cas:"24937-78-8",
    formula:['(C<sub>2</sub>H<sub>4</sub>)<sub>n</sub>', '(C<sub>4</sub>H<sub>6</sub>O<sub>2</sub>)<sub>m</sub>'],
    //  formula : "(C2H4)N or (C4H6O2)M",
    othernames:"Poly(ethylene-vinyl acetate)",
  },
  {
    id: 2,
    title: "Polyethelyne Terephthalate (PET Resin)",
    img: "./assets/images/Products-all-img/chemicals/polymers/polymer-2.webp",
    cas:"25038-59-9",
    formula:["C<sub>10</sub>H<sub>8</sub>O<sub>4</sub><sub>n</sub>"],
    // formula:"C10H8O4N",
    othernames:"Poly(ethyl-benzene-1,4-dicarboxylate)",

  },
  {
    id: 3,
    title: "Polyvinyl Chloride Resin (PVC Resin)",
    img:"./assets/images/Products-all-img/chemicals/polymers/polymer-3.webp",
    cas:"9002-86-2",
    formula:['(C<sub>2</sub>H<sub>3</sub>CL)<sub>n</sub>'],
    // formula:"(C2H3Cl)n",
    othernames:"poly(1-chloroethylene)",
  },
  
];
export const solvents = [
    {
      id: 1,
      title: "Acetone",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-1.webp",
      cas:"67-64-1",
      formula:['C<sub>3</sub>H<sub>6</sub>O',' or ', 'CH<sub>3</sub>COCH<sub>3</sub>'],
      // formula:"C3H6O or CH3COCH3",
      othernames:"Dimethyl ketone",
    },
    {
      id: 2,
      title: "Acetic Acid",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-2.webp",
      cas:"64-19-7",
      formula:['C<sub>2</sub>H<sub>4</sub>O<sub>2</sub>', ' or ', 'CH<sub>3</sub>COOH'],
      // formula:"C2H4O2 or CH3COOH",
      othernames:"Ethanoic acid",
    },
    {
      id: 3,
      title: "Acrylonitrile",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-3.webp",
      cas:"107-13-1",
      formula:['C<sub>3</sub>H<sub>3</sub>N', 'or ','H<sub>2</sub>(CH)CN'],
      // formula:"C3H3N or H2C(CH)CN",
      othernames:"Prop-2-enenitrile",
    },
    {
      id: 4,
      title: "Butyl Acetate",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-4.webp",
      cas:"79-06-1",
      formula:['C<sub>6</sub>H<sub>12</sub>O<sub>2</sub>',' or ', 'CH<sub>3</sub>COO(CH<sub>2</sub>)<sub>3</sub>CH<sub>3</sub>'],
      // formula:"C6H12O2 or CH3COO(CH2)3CH3",
      othernames:"Butyl ethanoate",
    },

    {
      id: 5,
      title: "Butyl Glycol",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-5.webp",
      cas:"111-76-2",
      formula:['C<sub>6</sub>H<sub>14</sub>O<sub>2</sub>'],
      // formula:"C6H14O2",
      othernames:"2-Butoxyethan-1-ol",
    },

    {
      id: 6,
      title: "C -IX",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-6.webp",
      cas:"64742-95-6",
      formula:['C<sub>9</sub>H<sub>12</sub>'],
      // formula:"C9H12",
      othernames:"Aromatic naphtha",
    },
    {
      id: 7,
      title: "Cyclohexanone",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-7.webp",
      cas:"108-94-1",
      formula:['C<sub>6</sub>H<sub>10</sub>O'],
      // formula:"C6H10O",
      othernames:"Pimelic ketone",
    },
    {
      id: 8,
      title: "Ethylene Di Chloride",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-8.webp",
      cas:"107-06-2",
      formula:['CLCH<sub>2</sub>CH<sub>2</sub>CL' , ' or ' , 'C<sub>2</sub>H<sub>4</sub>CL<sub>2</sub>'],
      // formula:"ClCH2CH2Cl or C2H4Cl2",
      othernames:"1,2-Dichloroethane",
    },
    {
      id: 9,
      title: "Iso Propyl Alcohol",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-9.webp",
      cas:"67-63-0",
      formula:['C<sub>3</sub>H<sub>8</sub>O'],
      // formula:"C3H8O",
      othernames:"Propan-2-o",
    },
    {
      id: 10,
      title: "Iso Butanol",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-10.webp",
      cas:"78-83-1",
      formula:['C<sub>4</sub>H<sub>10</sub>O',' or  ', '(CH<sub>3</sub>)<sub>2</sub>CHCH<sub>2</sub>OH'],
      // formula:"C4H10O or (CH3)2CHCH2OH",
      othernames:"2-Methyl-1-propanol, ",
    },
    {
      id: 11,
      title: "Methanol",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-11.webp",
      cas:"67-56-1",
      formula:['CH<sub>4</sub>O', '  or ','CH<sub>3</sub>OH'],
      // formula:"CH4O or CH3OH",
      othernames:"Columbian spirits",
    },
    {
      id: 12,
      title: "Methylene Di Chloride",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-12.webp",
      cas:"75-09-2",
      formula:['CH<sub>2</sub>CL<sub>2</sub>'],
      // formula:"CH2Cl2",
      othernames:"Dichloromethane",
    },
    {
      id: 13,
      title: "Methyl Ethyl Ketone",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-13.webp",
      cas:"78-93-3",
      formula:['C<sub>4</sub>H<sub>8</sub>O'],
      // formula:"C4H8O",
      othernames:"Butan-2-one;",
    },
    {
      id: 14,
      title: "Methy Iso Butyl Ketone",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-14.webp",
      cas:"108-10-1",
      formula:['C<sub>6</sub>H<sub>12</sub>'],
      // formula:"C6H12O",
      othernames:"4-Methylpentan-2-one",
    },
    {
      id: 15,
      title: "N Butanol",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-15.webp",
      cas:"71-36-3",
      formula:['C<sub>4</sub>H<sub>10</sub>O'],
      // formula:"C4H10O",
      othernames:"Butan-1-ol",
    },
    {
      id: 16,
      title:"N - Hexane",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-16.webp",
      cas:"110-54-3",
      formula:['C<sub>6</sub>H<sub>14</sub>'],
      // formula:"C6H14",
      othernames:"Skellysolve B",
    },
    {
      id: 17,
      title: "Phenol",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-17.webp",
      cas:"108-95-2",
      formula:['C<sub>6</sub>H<sub>6</sub>0',' or ' ,'C<sub>6</sub>H<sub>5</sub>OH'],
      // formula:"C6H6O or C6H5OH",
      othernames:"Benzenol",
    },
    {
      id: 18,
      title: "Toluene",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-18.webp",
      cas:"108-88-3",
      formula:['C<sub>6</sub>H<sub>5</sub>CH<sub>3</sub>', ' or ' , 'C<sub>7</sub>H'],
      // formula:"C6H5CH3 or C7H",
      othernames:"Methyl benzene",
    },
    {
      id: 19,
      title: "Vinyl Acetate Monomer",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-19.webp",
      cas:"108-05-4",
      formula:['C<sub>4</sub>H<sub>6</sub>O<sub>2</sub>'],
      // formula:"C4H6O2",
      othernames:"Ethenyl acetate",
    },
    {
      id: 20,
      title: "Xylene (Mix)",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-20.webp",
      cas:"1330-20-7",
      formula:['C<sub>24</sub>H<sub>30</sub>'],
      // formula:" C24H30",
      othernames:" 1,2-xylene",
    },
    {
      id: 21,
      title: "Xylene (Ortho)",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-21.webp",
      cas:"95-47-6",
      formula:['C<sub>6</sub>H<sub>4</sub>(CH<sub>3</sub>)<sub>2</sub>', ' or ','C<sub>8</sub>H<sub>10<sub>'],
      // formula:"C6H4(CH3)2 or C8H10",
      othernames:"O-Xylene",
    },
    {
      id: 22,
      title: "Acetone",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-22.webp",
      cas:"67-64-1",
      formula:['(CH<sub>3</sub>)<sub>2</sub>CO'],
      // formula:"(CH3)2CO",
      othernames:"Dimethyl carbony",
    },
    {
      id: 23,
      title: "Acetic Acid",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-23.webp",
      cas:"64-19-7",
      formula:['C<sub>2</sub>H<sub>4</sub>O<sub>2</sub>'],
      // formula:"C2H4O2",
      othernames:"Vinegar (when dilute)",
    },
    {
      id: 24,
      title: "Acrylonitrile",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-24.webp",
      cas:"107-13-1",
      formula:['CH<sub>2</sub>CHCN'],
      // formula:"CH2CHCN",
      othernames:"2-Propenenitrile",
    },
    {
      id: 25,
      title: "Acetonitrile",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-25.webp",
      cas:"75-05-8",
      formula:['C<sub>2</sub>H<sub>3</sub>N'],
      // formula:"C2H3N",
      othernames:"Cyanomethane",
    },
    {
      id: 26,
      title: "Butyl Acetate",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-26.webp",
      cas:"123-86-4",
      formula:['C<sub>6</sub>H<sub>12</sub>O<sub>2</sub>', 'CH<sub>3</sub>COO(CH<sub>2</sub>)<sub>3</sub>CH<sub>3</sub>'],
      // formula:"C6H12O2 or CH3COO(CH2)3CH3",
      othernames:"Butyl ethanoate",
    },
    {
      id: 27,
      title: "Butyl Acrylate",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-27.webp",
      cas:"141-32-2",
      formula:['C<sub>7</sub>H<sub>12</sub>O<sub>2</sub>'],
      // formula:" C7H12O2",
      othernames:"n-Butyl acrylate",
    },
    {
      id: 28,
      title: "Butyl Carbitol",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-28.webp",
      cas:"112-34-5",
      formula:['H<sub>2</sub>SO<sub>4</sub>', 'CO<sub>2</sub>'],
      // formula:"C8H18O3",
      othernames:"",
    },
    {
      id: 29,
      title: "Butyl Carbitol Acetate",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-29.webp",
      cas:"111-76-2",
      formula:['C<sub>10</sub>H<sub>20</sub>O<sub>4</sub>'],
      // formula:"C10H20O4",
      othernames:"2-(2-Butoxyethoxy)ethanol",
    },
    {
      id: 30,
      title: "Butyl Glycol/ Cellosolve",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-30.webp",
      cas:"111-76-2",
      formula:['C<sub>6</sub>H<sub>1</sub>O<sub>2</sub>'],
      // formula:"C6H14O2",
      othernames:"2-(2-Butoxyethoxy)ethyl acetate;",
    },
    {
      id: 31,
      title: "Butyl Cellosolve Acetate",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-31.webp",
      cas:"112-07-2",
      formula:['C<sub>8</sub>H<sub>16</sub>O<sub>3</sub>'],
      // formula:"C8H16O3",
      othernames:"Butoxyethyl acetate",
    },
    {
      id: 32,
      title: "Chloroform",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-32.webp",
      cas:"67-66-3",
      formula:['CHCL<sub>3</sub>'],
      // formula:"CHCl3",
      othernames:"trichloro-Trichloroform",
    },
    {
      id: 33,
      title: "Disopropyl Ether (DIPE)",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-33.webp",
      cas:"108-20-3",
      formula:['C<sub>6</sub>H<sub>14</sub>O'],
      // formula:"C6H14O",
      othernames:"Isopropyl ether",
    },
    {
      id: 34,
      title: "Dimethyl Acetamide",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-34.webp",
      cas:"127-19-5",
      formula:['C<sub>4</sub>H<sub>9</sub>NO', ' or ', 'CH<sub>3</sub>CON(CH<sub>3</sub>)<sub>2</sub>'],
      // formula:"C4H9NO or CH3CON(CH3)2",
      othernames:"N,N-Dimethylacetamide",
    },
    {
      id: 35,
      title: "Dimethyl Formamide",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-35.webp",
      cas:"68-12-2",
      formula:['C<sub>3</sub>H<sub>7</sub>NO', 'or','HCCON(CH<sub>3</sub>)<sub>2</sub>'],
      // formula:"C3H7NO or HCON(CH3)2",
      othernames:"N,N-Dimethylformamide",
    },
    {
      id: 36,
      title: "Dimethyl Sulfoxide",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-36.webp",
      cas:"67-68-5",
      formula:['C<sub>2</sub>H<sub>6</sub>S', '(CH<sub>3</sub>)<sub>2</sub>SO'],
      // formula:"C2H6OS or (CH3)2SO",
      othernames:"Methyl sulfoxide",
    },
    {
      id: 37,
      title: "E Ethyl Acetate",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-37.webp",
      cas:"141-78-6",
      formula:['C<sub>4</sub>H<sub>8</sub>O<sub>2</sub>', 'CH<sub>3</sub>COOC<sub>2</sub>H<sub>5</sub>'],
      // formula:"C4H8O2 or CH3COOC2H5",
      othernames:"Methyl sulfoxide",
    },
    {
      id: 38,
      title: "Heptane",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-38.webp",
      cas:"142-82-5",
      formula:['C<sub>7</sub>H<sub>16</sub>', 'CH<sub>3</sub>(CH<sub>2</sub>)<sub>5</sub>CH<sub>3</sub>'],
      // formula:"C7H16 or CH3(CH2)5CH3",
      othernames:"n-Heptane",
    },
    {
      id: 39,
      title: "Heptane S",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-39.webp",
      cas:"142-82-5",
      formula:['C<sub>7</sub>H<sub>16</sub>'],
      // formula:"C7H16",
      othernames:"n-Heptane",
    },
    {
      id: 40,
      title: "isobutanol",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-40.webp",
      cas:"78-83-1",
      formula:['C<sub>4</sub>H<sub>18</sub>O', 'or ', '(CH<sub>3</sub>)<sub>2</sub>CHCH<sub>2</sub>OH'],
      // formula:"C4H10O or (CH3)2CHCH2OH",
      othernames:"2-Methyl-1-propanol",
    },
    {
      id: 41,
      title: "Methyl Ethyl Ketone",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-41.webp",
      cas:"78-93-3",
      formula:['C<sub>4</sub>H<sub>8</sub>O'],
      // formula:"C4H8O",
      othernames:"Butan-2-one",
    },
    {
      id: 42,
      title: "Isopropyl Alcohol",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-42.webp",
      cas:"67-63-0",
      formula:['C<sub>3</sub>H<sub>8</sub>O'],
      // formula:"C3H8O",
      othernames:"Propan-2-ol",
    },
    {
      id: 43,
      title: "N Butanol",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-43.webp",
      cas:"71-36-3",
      formula:['C<sub>4</sub>H<sub>10</sub>0'],
      // formula:"C4H10O",
      othernames:" 2-Propyl ethanoate",
    },
    {
      id: 44,
      title: "Isopropyl Acetate",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-44.webp",
      cas:"108-21-4",
      formula:['C<sub>5</sub>H<sub>10</sub>O<sub>2</sub>'],
      // formula:"C5H10O2",
      othernames:"Propan-2-yl acetate;",
    },
    {
      id: 45,
      title: "Methyl Ethyl Ketone",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-45.webp",
      cas:"78-93-3",
      formula:['C<sub>4</sub>H<sub>1</sub>O'],
      // formula:"C4H10O",
      othernames:"4-Methylpentan-2-one",
      },
    {
      id: 46,
      title: "Methy Iso Butyl Ketone",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-46.webp",
      cas:"108-10-1",
      formula:['C<sub>6</sub>H<sub>12</sub>O'],
      // formula:"C6H12O",
      othernames:"Hexone",
    },
    {
      id: 47,
      title: "Methyl Tertiary Butyl Ether (MTBE)",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-47.webp",
      cas:"1634-04-4",
      formula:['CSH<sub>12</sub>O'],
      // formula:"C5H12O",
      othernames:"2-Methoxy-2-methylpropane",
    },
    {
      id: 48,
      title: "Methylene Chloride",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-48.webp",
      cas:"75-09-2",
      formula:['CH<sub>2</sub>CL<sub>2</sub>'],
      // formula:"CH2Cl2",
      othernames:"Dichloromethane;",
    },
    {
      id: 49,
      title: "Monoglyme",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-49.webp",
      cas:"110-71-4",
      formula:['C<sub>4</sub>H<sub>10</sub>2'],
      // formula:"C4H10O2",
      othernames:"Ethylene glycol dimethyl ether",
    },
    {
      id: 50,
      title: "N - Methyl - 2 - Pyrrolidone (NMP)",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-50.webp",
      cas:"872-50-4",
      formula:['C<sub>5</sub>H<sub>9</sub>NO'],
      // formula:"C5H9NO",
      othernames:"1-Methylpyrrolidin-2-one",
    },
    {
      id: 51,
      title: "N - Pentane",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-51.webp",
      cas:"109-66-0",
      formula:['C<sub>5</sub>H<sub>12</sub>'],
      // formula:"C5H12",
      othernames:"Skellysolve A",
    },
    {
      id: 52,
      title: "N - Propanol",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-52.webp",
      cas:"71-23-8",
      formula:['C<sub>3</sub>H<sub>8</sub>O'],
      // formula:"C3H8O",
      othernames:"Propan-1-ol",
    },
    {
      id: 53,
      title: "N - Propyl Acetate",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-53.webp",
      cas:"109-60-4",
      formula:['C<sub>5</sub>H<sub>10</sub>O<sub>2</sub>'],
      // formula:"C5H10O2",
      othernames:"Acetic acid",
    },
    {
      id: 54,
      title: "N- Butanol",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-54.webp",
      cas:"71-36-3",
      formula:['C<sub>4</sub>H<sub>10</sub>O'],
      // formula:"C4H10O",
      othernames:"Butan-1-ol",
    },
    {
      id: 55,
      title: "N - Hexane 99%",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-55.webp",
      cas:"110-54-3",
      formula:['C<sub>6</sub>H<sub>14</sub>'],
      // formula:"C6H14",
      othernames:"Skellysolve B",
    },
    {
      id: 56,
      title: "N - Heptane",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-56.webp",
      cas:"142-82-5",
      formula:['C<sub>7</sub>H<sub>1</sub>6'],
      // formula:"C7H16",
      othernames:"Heptan",
    },
    {
      id: 57,
      title: "Perchloroethylene",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-57.webp",
      cas:"127-18-4",
      formula:['H<sub>2</sub>SO<sub>4</sub>', 'CO<sub>2</sub>'],
      // formula:" C2Cl4",
      othernames:"Tetrachloroethene",
    },
    { 
      id: 58,
      title: "Phenol",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-58.webp",
      cas:"108-95-2",
      formula:['C<sub>6</sub>H<sub>6</sub>O', 'or ' ,  'C<sub>6</sub>H<sub>5</sub>OH'],
      // formula:"C6H6O or C6H5OH",
      othernames:"Carbolic acid",
    },
    {
      id: 59,
      title: "Tertiary Butyl Acetate",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-59.webp",
      cas:"540-88-5",
      formula:['C<sub>6</sub>H<sub>12</sub>O<sub>2</sub>'],
      // formula:"C6H12O2",
      othernames:"1,1-dimethylethyl acetate",
    },
    {
      id: 60,
      title: "Tetrahydrofuran",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-60.webp",
      cas:"109-99-9",
      formula:['C<sub>4</sub>H<sub>4</sub>O', '(CH<sub>2</sub>)<sub>3</sub>CH<sub>2</sub>o'],
      // formula:"C4H8O or (CH2)3CH2O",
      othernames:" Butylene oxide",
    },
    {
      id: 61,
      title: "Trichloroethylene",
      img:"./assets/images/Products-all-img/chemicals/solvent/solvent-61.webp",
      cas:"79-01-6",
      formula:['C<sub>2</sub>HC<sub>13</sub>'],
      // formula:" C2HCl3",
      othernames:"1,1,2-Trichloroethene;",
    },

  ];
  export const chemicalsAndIntermediates = [
    {
      id: 1,
      title: " Bromo 3- Chloropropane",
      img:"./assets/images/Products-all-img/chemicals/chemicalAndintermediates/ci-1.webp",
      cas:": 109-70-6",
      formula:['C<sub>3</sub>H<sub>6</sub>BRCL'],
      // formula:": C3H6BrCl ",
      othernames:"3-Bromopropyl chloride",
    },
    {
      id: 2,
      title: "H Triazole",
      img:"./assets/images/Products-all-img/chemicals/chemicalAndintermediates/ci-2.webp",
      cas:"288-88-0",
      formula:['C<sub>2</sub>H<sub>3</sub>N<sub>3</sub>'],
      // formula:"C2H3N3 ",
      othernames:" 1H-1,2,4-Triazole",
    },
    {
      id: 3,
      title: "Butanediol",
      img:"./assets/images/Products-all-img/chemicals/chemicalAndintermediates/ci-3.webp",
      cas:": 110-63-4",
      formula:['HOCH<sub>2</sub>CH<sub>2</sub>CH<sub>2</sub>CH<sub>2</sub>OH'],
      // formula:"HOCH2CH2CH2CH2OH",
      othernames:": Tetramethylene Glycol",
    },
    {
      id: 4,
      title: "Dioxane",
      img:"./assets/images/Products-all-img/chemicals/chemicalAndintermediates/ci-4.webp",
      cas:" 123-91-1",
      formula:['C<sub>4</sub>H<sub>4</sub>O<sub>2</sub>'],
      // formula:"C4H4O2",
      othernames:" Dioxán,1, 4-Dioxane, 1",
    },
    {
      id: 5,
      title: "Hexanediol",
      img:"./assets/images/Products-all-img/chemicals/chemicalAndintermediates/ci-5.webp",
      cas:"629-11-8",
      formula:['C<sub>6</sub>H<sub>14</sub>O<sub>2</sub>', 'CO<sub>2</sub>'],
      // formula:"C6H14O2",
      othernames:"Hexamethylene glycol",
    },
    {
      id: 6,
      title: "Ethyl Hexanoic acid",
      img:"./assets/images/Products-all-img/chemicals/chemicalAndintermediates/ci-6.webp",
      cas:"149-57-5",
      formula:['CH<sub>3</sub>(CH<sub>2</sub>)3CH(C<sub>2</sub>H<sub>5</sub>)CO<sub>2</sub>H'],
      // formula:"CH3(CH2)3CH(C2H5)CO2H",
      othernames:"Trimethylene bromochloride",
    },
    {
      id: 7,
      title: "Ethyl Hexyl Acrylate",
      img:"./assets/images/Products-all-img/chemicals/chemicalAndintermediates/ci-7.webp",
      cas:"103-11-7",
      formula:['C<sub>11</sub>H<sub>20</sub>O<sub>2</sub>'],
      // formula:"C11H20O2",
      othernames:"2-Ethylhexyl acrylate",
    },
    {
      id: 8,
      title: "Methyl THF",
      img:"./assets/images/Products-all-img/chemicals/chemicalAndintermediates/ci-8.webp",
      cas:"96-47-9",
      formula:['C<sub>5</sub>H<sub>10</sub>O'],
      // formula:"C5H10O",
      othernames:"2-methyl Tetrahydrofuran",
    },
    {
      id: 9,
      title: "Hydroxy Ethyl Mathacrylate",
      img:"./assets/images/Products-all-img/chemicals/chemicalAndintermediates/ci-9.webp",
      cas:"868-77-9",
      formula:['C<sub>6</sub>H<sub>10</sub>0<sub>3</sub>'],
      // formula:"C6H10O3",
      othernames:"2-Hydroxyethyl Methacrylate",
    },
    {
      id: 10,
      title: "Di Methoxy Propane",
      img:"./assets/images/Products-all-img/chemicals/chemicalAndintermediates/ci-10.webp",
      cas:"77-76-9 ",
      formula:['C<sub>5</sub>H<sub>12</sub>0<sub>2</sub>', 'CO<sub>2</sub>'],
      // formula:"C5H12O2",
      othernames:"Acetone dimethyl acetal",
    },
    {
      id: 11,
      title: "Di Methoxy Propane",
      img:"",
      cas:"77-76-9 ",
      formula:['H<sub>2</sub>SO<sub>4</sub>', 'CO<sub>2</sub>'],
      // formula:"C5H12O2",
      othernames:"2, 4-Dichlorobenzyl chloride",

    },
    {
      id: 12,
      title: "Dichloro Benzyl Chloride",
      img:"",
      cas:"94-99-5",
      formula:['H<sub>2</sub>SO<sub>4</sub>', 'CO<sub>2</sub>'],
      // formula:"C7H5Cl3",
      othernames:"",

    },
    {
      id: 13,
      title: "Di Methyl Amino Pyridine",
      img:"",
      cas:"1122-58-3",
      formula:['C<sub>7</sub>H<sub>10</sub>N<sub>2</sub>'],
      // formula:"C7H10N2",
      othernames:"4-Dimethylaminopyridine",

    },
    {
      id: 14,
      title: "Hydroxy Benzaldehyde",
      img:"",
      cas:"123-08-0",
      formula:['C<sub>7</sub>H<sub>6</sub>O<sub>2</sub',],
      // formula:"C7H6O2",
      othernames:"p-Hydroxybenzaldehyde",

    },
    {
      id: 15,
      title: "Acetophenone",
      img:"",
      cas:"98-86-2",
      formula:['C<sub>6</sub>H<sub>5</sub>C(O)CH<sub>3</sub>'],
      // formula:"C6H5C(O)CH3",
      othernames:"Acetone",
    },
    {
      id: 16,
      title: "Acrylamide",
      img:"",
      cas:"79-06-1",
      formula:['C<sub>3</sub>H<sub>5</sub>NO'],
      // formula:"C3H5NO",
      othernames:"Acrylamide(8CI)",
    },
    {
      id: 17,
      title: "Acrylic Acid",
      img:"",
      cas:"79-10-7",
      formula:['C<sub>3</sub>H<sub>4</sub>O<sub>2</sub>'],
      // formula:"C3H4O2",
      othernames:"2-Propenoic acid",
    },
    {
      id: 18,
      title: "Adipic Acid",
      img:"",
      cas:"124-04-9",
      formula:['C<sub>6</sub>H<sub>10</sub>O<sub>4</sub>'],
      // formula:"C6H10O4",
      othernames:"Adipic Acid",
    },
    {
      id: 19,
      title: "Allyl Alcohol",
      img:"",
      cas:"107-18-6",
      formula:['H<sub>2</sub>SO<sub>4</sub>', 'CO<sub>2</sub>'],
      // formula:"C3H6O",
      othernames:"",
    },
    {
      id: 20,
      title: "Alpha Naphthol",
      img:"",
      cas:"90-15-3",
      formula:['C<sub>10</sub>H<sub>8</sub>O'],
      // formula:"C10H8O",
      othernames:"alpha-naphthol",
    },
    {
      id: 21,
      title: "Ammonium Bi Carbonate",
      img:"",
      cas:"1066-33-7",
      formula:['NH<sub>4</sub>HCO'],
      // formula:"NH4HCO",
      othernames:"Ammonium hydrogen carbonate,",
    },
    {
      id: 22,
      title: "Ammonium Thiocyanate",
      img:"",
      cas:"1762-95-4 ",
      formula:['NH<sub>4</sub>SCN'],
      // formula:"NH4SCN or CH4N2S",
      othernames:"Ammonium isothiocyanate,",
    },
    {
      id: 23,
      title: "Amino Ethylethanolamine",
      img:"",
      cas:"111-41-1",
      formula:['H<sub>2</sub>SO<sub>4</sub>', 'CO<sub>2</sub>'],
      // formula:"C4H12N2O",
      othernames:"",
    },
    {
      id: 24,
      title: "Amino Guanidine Bicarbonate",
      img:"",
      cas:"2582-30-1",
      formula:['H<sub>2</sub>SO<sub>4</sub>', 'CO<sub>2</sub>'],
      // formula:"C2H8N4O3",
      othernames:"",
    },
    {
      id: 25,
      title: "Aniline Oil",
      img:"",
      cas:"62-53-3",
      formula:['H<sub>2</sub>SO<sub>4</sub>', 'CO<sub>2</sub>'],
      // formula:"C6H5NH2",
      othernames:"",
    },
    {
      id: 26,
      title: "Benzoic Acid",
      img:"",
      cas:"65-85-0",
      formula:['C<sub>7</sub>H<sub>6</sub>O<sub>2</sub>', ' or ', 'C<sub>6</sub>H<sub>5</sub>COOH'],
      // formula:"C7H6O2 or C6H5COOH",
      othernames:"Carboxybenzene",
    },
    {
      id: 27,
      title: "Benzophenone",
      img:"",
      cas:"119-61-9",
      formula:['C<sub>13</sub>H<sub>10</sub>'],
      // formula:"C13H10O or C6H5COC6H5",
      othernames:"Diphenyl ketone",
    },
    {
      id: 28,
      title: "Benzylamine",
      img:"",
      cas:"100-46-9",
      formula:['C<sub>7</sub>H<sub>9</sub>N', ' or ', 'C<sub>6</sub>H<sub>5</sub>CH<sub>2</sub>NH<sub>2</sub>'],
      // formula:": C7H9N or C6H5CH2NH2",
      othernames:"Aminotoluene",
    },
    {
      id: 29,
      title: "Beta Naphthol",
      img:"",
      cas:"135-19-3",
      formula:['C<sub>10</sub>H<sub>8</sub>O'],
      // formula:"C10H8O",
      othernames:"Bis(trichloromethyl) carbonate",
    },
    {
      id: 30,
      title: "Bis Trichloro Methyl Carbonate",
      img:"",
      cas:"79-06-1",
      formula:['C<sub>3</sub>CL<sub>6</sub>O'],
      // formula:"C3Cl6O",
      othernames:" Bis(trichloromethyl) carbonate,",
    },
    {
      id: 31,
      title: "Bisphenol A",
      img:"",
      cas:"80-05-7",
      formula:['C<sub>15</sub>H<sub>16</sub>O<sub>2</sub>','or', '(CH<sub>3</sub>)2C(C<sub>6</sub>H<sub>4</sub)<sub>2</sub>'],
      // formula:"C15H16O2 or (CH3)2C(C6H4OH)2",
      othernames:"2,2-Bis(4-hydroxyphenyl)propane",
    },
    {
      id: 32,
      title: "Caustic Potash Flakes",
      img:"",
      cas:"1310-58-3",
      formula:['KOH'],
      // formula:"KOH",
      othernames:"Potassium hydroxide",
    },
    {
      id: 33,
      title: "Citric Acid Anhydrous",
      img:"",
      cas:"77-92-9",
      formula:['C<sub>6</sub>H<sub>8</sub>O<sub>7</sub>'],
      // formula:"C6H8O7",
      othernames:"Citric acid,",
    },
    {
      id: 34,
      title: "Citric Acid Monohydrate",
      img:"",
      cas:"5949-29-1",
      formula:['C<sub>3</sub>H<sub>4</sub>N<sub>2</sub>O'],
      // formula:"C3H4N2O",
      othernames:"Citric acid hydrate,",
    },
    {
      id: 35,
      title: "Cyano Acetamide",
      img:"",
      cas:"107-91-5",
      formula:['C<sub>3</sub>H<sub>4</sub>N<sub>2</sub>O'],
      // formula:" C3H4N2O",
      othernames:": 2-Cyanoacetamide",
    },
    {
      id: 36,
      title: "Cyclohexane",
      img:"",
      cas:"110-82-7",
      formula:['C<sub>6</sub>H<sub>12</sub>'],
      // formula:" C6H12",
      othernames:"Hexamethylene",
    },
    {
      id: 37,
      title: "Cyclohexanol",
      img:"",
      cas:"108-93-0",
      formula:['C<sub>6</sub>H<sub>12</sub>O'],
      // formula:"C6H12O",
      othernames:"Cyclohexyl alcohol",
    },
    {
      id: 38,
      title: "Cyclohexanone",
      img:"",
      cas:"108-94-1",
      formula:['C<sub>6</sub>H<sub>10</sub>O'],
      // formula:": C6H10O",
      othernames:"Pimelic ketone",
    },
    {
      id: 39,
      title: "Cyclohexylamine",
      img:"",
      cas:"108-91-8",
      formula:['C<sub>62</sub>H<sub>13</sub>N'],
      // formula:":  C6H13N",
      othernames:"Cyclopropylamine",
    },
    {
      id: 40,
      title: "Cyclopropylamine",
      img:"",
      cas:"765-30-0",
      formula:['C<sub>3</sub>H<sub>7</sub>N'],
      // formula:"C3H7N",
      othernames:"Cyclopropylamine",
    },
    {
      id: 41,
      title: "D- Tartaric Acid",
      img:"",
      cas:"526-83-0",
      formula:['C<sub>4</sub>H<sub>6</sub>O<sub>6</sub>'],
      // formula:"C4H6O6",
      othernames:"Tartaric acid",
    },
    {
      id: 42,
      title: "Di Acetone",
      img:"",
      cas:"123-42-2",
      formula:['C<sub>6</sub>H<sub>12</sub>O<sub>2</sub>'],
      // formula:"C6H12O2",
      othernames:"4-Hydroxy-4-methylpentan-2-one",
    },
    {
      id: 43,
      title: "Di Cyclohexylamine",
      img:"",
      cas:"101-83-7",
      formula:['C<sub>12</sub>H<sub>23</sub>N'],
      // formula:"C12H23N",
      othernames:"N-Cyclohexylcyclohexanamine",
    },
    {
      id: 44,
      title: "Di Cyclohexylcarbodiimide",
      img:"",
      cas:"538-75-0",
      formula:['C<sub>13</sub>H<sub>2</sub>N<sub>2</sub>'],
      // formula:"C13H22N2",
      othernames:"N,N'-Dicyclohexylcarbodiimide",
    },
    {
      id: 45,
      title: "Di Ehtyl Ether",
      img:"",
      cas:"60-29-7",
      formula:['C<sub>4</sub>H<sub>18</sub>O'],
      // formula:"C4H10O ",
      othernames:"Ethyl ether",
    },
    {
      id: 46,
      title: "Di Ehtyl Sulphate",
      img:"",
      cas:"64-67-5",
      formula:['C<sub>4</sub>H<sub>10</sub>O<sub>4</sub>s', 'or', '(C<sub>2</sub>H<sub>5</sub>)2SO'],
      // formula:"C4H10O4S or (C2H5)2SO",
      othernames:"Sulfuric acid diethyl ester",
    },
    {
      id: 47,
      title: "Di Ethylamine",
      img:"",
      cas:"109-89-7",
      formula:['C<sub>4</sub>H<sub>11</sub>N'],
      // formula:"C4H11N",
      othernames:"N-Ethylamine",
    },
    {
      id: 48,
      title: "Di Ethanolamine",
      img:"",
      cas:"111-42-2",
      formula:['C<sub>4</sub>H<sub>11</sub>NO<sub>2</sub>'],
      // formula:"C4H11NO2",
      othernames:"2,2'-Iminodiethanol",
    },
    {
      id: 49,
      title: "Di Ethyl Carbonate",
      img:"",
      cas:"105-58-8",
      formula:['C<sub>5</sub>H<sub>10</sub>O<sub>3</sub>',' or ','(C<sub>2</sub>H<sub>5</sub>O)<sub>2</sub>CO'],
      // formula:"C5H10O3 or (C2H5O)2CO",
      othernames:"Ethyl carbonate",
    },
    {
      id: 50,
      title: "Di Ethyl Malonate",
      img:"",
      cas:"105-53-3",
      formula:['C<sub>7</sub>H<sub>12</sub>O<sub>4</sub>'],
      // formula:" C7H12O4",
      othernames:"Ethyl carbonate",
    },
    {
      id: 51,
      title: "Di Ethylene Triamine",
      img:"",
      cas:"1 05-53-3",
      formula:['C<sub>4</sub>H<sub>13</sub>N<sub>3</sub>'],
      // formula:" C4H13N3",
      othernames:"Bis(2-aminoethyl)amine",
    },

    {
      id: 52, 
      title: "Di Iso Propyl Ether",
      img:"",
      cas:"108-20-3",
      formula:['C<sub>6</sub>H<sub>14</sub>O'],
      // formula:"C6H14O",
      othernames:"Isopropyl ether",
    },
   
    {
      id: 53,
      title: "Di Iso Propylamine",
      img:"",
      cas:"108-18-9",
      formula:['C<sub>6</sub>H<sub>1</sub>N'],
      // formula:"C6H15N",
      othernames:"Isopropyl ether",
    },
    {
      id: 54,
      title: "Di Methyl Amine 40%",
      img:"",
      cas:"124-40-3",
      formula:['(CH<sub>3</sub>)<sub>2</sub>NH', ' or ','C<sub>2</sub>H<sub>7</sub>N'],
      // formula:"(CH3)2NH or C2H7N",
      othernames:"N-Methylmethanamine",
    },
    {
      id: 55,
      title: "Di Methyl Carbonate",
      img:"",
      cas:"616-38-6",
      formula:['C<sub>3</sub>H<sub>6</sub>O<sub></sub>'],
      // formula:" C3H6O3",
      othernames:"Methyl carbonate",
    },
    {
      id: 56,
      title: "Di Methyl Malonate",
      img:"",
      cas:"108-59-8",
      formula:['H<sub>2</sub>SO<sub>4</sub>', 'CO<sub>2</sub>'],
      // formula:"C5H8O",
      othernames:"Dimethyl propanedioate",
    },
    {
      id: 57,
      title: "Di N Butylamine",
      img:"",
      cas:"111-92-2",
      formula:['H<sub>2</sub>SO<sub>4</sub>', 'CO<sub>2</sub>'],
      // formula:" C8H19N",
      othernames:"di-Normal-butylamine",
    },
    {
      id: 58,
      title: "Di Propylene Glycol",
      img:"",
      cas:"25265-71-8",
      formula:['C<sub>6</sub>H<sub>14</sub>O<sub>3</sub>'],
      // formula:"C6H14O3",
      othernames:"1,1'-Oxybis(2-propanol)",
    },
    {
      id: 59,
      title: "Di Tret Butyl Dicarbonate",
      img:"",
      cas:"24424-99-5",
      formula:['C<sub>10</sub>H<sub>10</sub>O<sub>5</sub>'],
      // formula:"C10H18O5",
      othernames:"BOC anhydride",
    },
    {
      id: 60,
      title: "Dicyandiaminde",
      img:"",
      cas:"461-58-5",
      formula:['H<sub>2</sub>SO<sub>4</sub>', 'CO<sub>2</sub>'],
      // formula:"C2H4N4",
      othernames:"Dicyanodiamide",
    },
    {
      id: 61,
      title: "Epichlorohydrin",
      img:"",
      cas:"106-89-8",
      formula:['C<sub>3</sub>H<sub>5</sub>CLO'],
      // formula:"C3H5ClO",
      othernames:"Chloromethyl)oxirane;",
    },
    {
      id: 62,
      title: "Epoxy Resin",
      img:"",
      cas:"25068-38-6",
      formula:['C<sub>21</sub>H<sub>25</sub>CIO<sub>5</sub>'],
      // formula:"C21H25ClO5",
      othernames:"ED 20 acrylate;",
    },
    {
      id: 63,
      title: "Ethyl Acetate",
      img:"",
      cas:"141-78-6",
      formula:['H<sub>2</sub>SO<sub>4</sub>', 'CO<sub>2</sub>'],
      // formula:"C4H8O2 or CH3COOC2H5",
      othernames:"",
    },
    {
      id: 64,
      title: "Ethyl Acetate",
      img:"",
      cas:"141-78-6",
      formula:['C<sub>4</sub>H<sub>8</sub>O<sub>2</sub>', 'or ', 'CH<sub>3</sub>COOC<sub>2</sub>H<sub>5</sub>'],
      // formula:"C4H8O2 or CH3COOC2H5",
      othernames:"Ethyl ethanoate",
    },
    {
      id: 65,
      title: "Ethyl Aceto Acetate",
      img:"",
      cas:"141-97-9",
      formula:['C<sub>6</sub>H<sub>10</sub>O<sub>3</sub>'],
      // formula:"C6H10O3",
      othernames:"Ethyl 3-oxobutanoate",
    },
    {
      id: 66,
      title: "Ethyl Acrylate",
      img:"",
      cas:"140-88-5",
      formula:['C<sub>5</sub>H<sub>8</sub>O<sub>2</sub>'],
      // formula:"C5H8O2",
      othernames:"Acrylic acid ethyl ester",
    },
    {
      id: 67,
      title: "Ethyl Chloro Formate",
      img:"",
      cas:"541-41-3",
      formula:['H<sub>2</sub>SO<sub>4</sub>', 'CO<sub>2</sub>'],
      // formula:"C3H5ClO2 or ClCOOC2H5",
      othernames:"",
    },
    {
      id: 68,
      title: "Ethyl Cyano Acetate",
      img:"",
      cas:"105-56-6",
      formula:['C<sub>5</sub>H<sub>7</sub>NO<sub>2</sub>'],
      // formula:"C5H7NO2",
      othernames:"Ethyl carbonochloridate",
    },
    {
      id: 69,
      title: "Ethylene Diamine (EDA)",
      img:"",
      cas:"107-15-3",
      formula:['C<sub>2</sub>H<sub>8</sub>N'],
      // formula:"C2H8N",
      othernames:"Ethane-1,2-diamine",
    },
    {
      id: 70,
      title: "Fluorobenzene",
      img:"",
      cas:"462-06-6",
      formula:['C<sub>6</sub>H<sub>5</sub>F'],
      // formula:"C6H5F",
      othernames:"Ethane-1,2-diamine",
    },
    {
      id: 71,
      title: "Formamide",
      img:"",
      cas:"75-12-7",
      formula:['CH<sub>3</sub>NO'],
      // formula:"CH3NO or HCONH2",
      othern1ames:"Phenyl fluoride",
    },
    {
      id: 72,
      title: "Formic Acid 85%",
      img:"",
      cas:"75-12-7",
      formula:['CH<sub>3</sub>NO', ' or ','HCNOH<sub>2</sub>'],
      // formula:"CH3NO or HCONH2",
      othernames:"Methanamide",
    },
    {
      id: 73,
      title: "Fumaric Acid",
      img:"",
      cas:"110-17-8",
      formula:['C<sub>4</sub>H<sub>4</sub>O<sub>4</sub>'],
      // formula:"C4H4O4",
      othernames:" Formimidic acid",
    },
    {
      id: 74,
      title: "Furfuryl Alcohol",
      img:"",
      cas:"98-00-0",
      formula:['C<sub>5</sub>H<sub>6</sub>O<sub>2</sub>'],
      // formula:"C5H6O2",
      othernames:"Furan-2-ylmethanol; 2",
    },
    {
      id: 75,
      title: "Glycerine",
      img:"",
      cas:"56-81-5",
      formula:['C<sub>3</sub>H<sub>8</sub>O<<sub>3</sub>'],
      // formula:"C3H8O3",
      othernames:"Glycerol;",
    },
    {
      id: 76,
      title: "Hexamethyldisilazane",
      img:"",
      cas:"999-97-3",
      formula:['C<sub>6</sub>H<sub>19</sub>'],
      // formula:"C6H19NSi2",
      othernames:" Bis(Trimethylsilyl)Amine",
    },
    {
      id: 77,
      title: "Hexylene Glycol",
      img:"",
      cas:"107-41-5",
      formula:['C<sub>6</sub>H<sub>14</sub>O<sub>2</sub>'],
      // formula:"C6H14O2",
      othernames:"2,4-Dihydroxy-2-methylpentane;",
    },
    {
      id: 78,
      title: "Hydrogen Peroxide",
      img:"",
      cas:"7722-84-1",
      formula:['H<sub>2</sub>O<sub>2</sub>'],
      // formula:"H2O2",
      othernames:"Oxydo",
    },
    {
      id: 79,
      title: "Hydroquinone",
      img:"",
      cas:"123-31-9",
      formula:['C<sub>6</sub>H<sub>6</sub>O<sub>2</sub>',' or ','C<sub>6</sub>H<sub>4</sub>(OH)<sub>2</sub>'],
      // formula:"C6H6O2 or C6H4(OH)2",
      othernames:"Benzene-1,4-diol;",
    },
    {
      id: 80,
      title: "Hydroxylamine HCl",
      img:"",
      cas:"5470-11-1",
      formula:['C<sub>1</sub>H<sub>7</sub>N<sub>2</sub>O'],
      // formula:"ClH7N2O",
      othernames:"Hydroxylammonium Chloride",
    },
    {
      id: 81,
      title: "Hydroxylamine Sulphate",
      img:"",
      cas:"10039-54-0",
      formula:['(NH<sub>2</sub>OH)<sub>2</sub>.H<sub>2</sub>SO<sub>4</sub>', ' or ','HBN<sub>2</sub>O<sub>6</sub>S'],
      // formula:"(NH2OH)2.H2SO4 or H8N2O6S",
      othernames:"Oxammonium sulfate;",
    },
    {
      id: 82,
      title: "Hexamine",
      img:"",
      cas:"100-97-0",
      formula:['C<sub>6</sub>H<sub>12</sub>N<sub>4</sub>'],
      // formula:"C6H12N4",
      othernames:"Methenamine",
    },
    {
      id: 83,
      title: "Imidazole",
      img:"",
      cas:"288-32-4",
      formula:['C<sub>3</sub>H<sub>4</sub>N<sub>2</sub>'],
      // formula:"C3H4N2",
      othernames:"Glyoxaline",
    },
    {
      id: 84,
      title: "Iodine",
      img:"",
      cas:"7553-56-2",
      formula:['I<sub>2</sub>'],
      // formula:"I2",
      othernames:"Vistarin",
    },
    {
      id: 85,
      title: "Isobutanol",
      img:"",
      cas:"78-83-1",
      formula:['C<sub>4</sub>H<sub>10</sub>O', ' or ', '(CH<sub>3</sub>)<sub>2</sub>CHCH<sub>2</sub>OH'],
      // formula:"C4H10O or (CH3)2CHCH2OH",
      othernames:"2-Methyl-1-propanol",
    },
    {
      id: 86,
      title: "Iso Butyrlic Acid",
      img:"",
      cas:"79-31-2",
      formula:['H<sub>2</sub>SO<sub>4</sub>', 'CO<sub>2</sub>'],
      // formula:"C4H8O2",
      othernames:"",
    },
    {
      id: 87,
      title: "Iso Butyrlic Acid",
      img:"",
      cas:"79-31-2",
      formula:['C<sub>4</sub>H<sub>8</sub>O<sub>2</sub>'],
      // formula:"C4H8O2",
      othernames:" Isobutyl alcohol",
    },
    {
      id: 88,
      title: "Iso Propyl Alcohol",
      img:"",
      cas:"67-63-0",
      formula:['C<sub>3</sub>H<sub>8</sub>O'],
      // formula:"C3H8O",
      othernames:"Propan-2-o",
    },
    {
      id: 89,
      title: "Isopropyl Acetate",
      img:"",
      cas:"108-21-4",
      formula:['  C<sub>5</sub>H<sub>10</sub>O<sub>2</sub>'],
      // formula:"C5H10O2",
      othernames:"Propan-2-yl acetate",
    },
    {
      id: 90,
      title: "Isobutyraldehyde",
      img:"",
      cas:"78-84-2",
      formula:['C<sub>4</sub>H<sub>8</sub>O'],
      // formula:"C4H8O",
      othernames:"2-Methylpropana",
    },
    {
      id: 91,
      title: "Isophorone",
      img:"",
      cas:"78-59-1",
      formula:['C<sub>9</sub>H<sub>14</sub>O'],
      // formula:"C9H14O",
      othernames:"Isoacetophorone",
    },
    {
      id: 92,
      title: "Isophorone Diamine",
      img:"",
      cas:"2855-13-2",
      formula:['C<sub>10</sub>H<sub>22</sub>N<sub>2</sub>'],
      // formula:"C10H22N2",
      othernames:"3-(Aminomethyl)-3,5,5-trimethylcyclohexan-1-amine",
    },
    {
      id: 93,
      title: "Isophorone Diamine",
      img:"",
      cas:"2855-13-2",
      formula:['C<sub>10</sub>SO<sub>4</sub>', 'CO<sub>2</sub>'],
      // formula:"C10H22N2",
      othernames:"Benzene-1,3-dicarboxylic acid",
    },
    {
      id: 94,
      title: "Isophthalic Acid",
      img:"",
      cas:"121-91-5",
      formula:['C<sub>8</sub>H<sub>6</sub>O<sub>4</sub>', ],
      // formula:" C8H6O4",
      othernames:" m-Benzenedicarboxylic acid",
    },
    {
      id: 95,
      title: "Isovaleraldehyde",
      img:"",
      cas:"590-86-3",
      formula:['C<sub>5</sub>H<sub>10</sub>O'],
      // formula:" C5H10O",
      othernames:" Isoamylaldehyde",
    },
    {
      id: 96,
      title: "L - Tartaric Acid",
      img:"",
      cas:"526-83-0",
      formula:['C<sub>4</sub>H<sub>6</sub>O<sub>6</sub>'],
      // formula:"C4H6O6",
      othernames:" Uvic acid",
    },
    {
      id: 97,
      title: "Lactose",
      img:"",
      cas:"63-42-3",
      formula:['C<sub>12</sub>H<sub>22</sub>O<sub>11</sub>'],
      // formula:" C12H22O11",
      othernames:"D-Lactose",
    },
    {
      id: 98,
      title: "Lithium Carbonate",
      img:"",
      cas:"554-13-2",
      formula:['L1<sub>2</sub>CO<sub>3</sub>',' or ', 'CLI<sub>2</sub>O<sub>3x</sub>'],
      // formula:"Li2CO3 or CLi2O3",
      othernames:"Dilithium carbonate",
    },
    {
      id: 99,
      title: "Lithium Hydroxide",
      img:"",
      cas:"1310-65-2",
      formula:['LIOH', ' or ', 'HLIO'],
      // formula:"LiOH or HLiO",
      othernames:"Lithium hydroxide anhydrous",
    },
    {
      id: 100,
      title: "Maliec Anhydride",
      img:"",
      cas:"108-31-6",
      formula:['C<sub>4</sub>H<sub>2</sub>O<sub>3</sub>'],
      // formula:"C4H2O3",
      othernames:"Furan-2,5-dione",
    },
    {
      id: 101,
      title: "Malonic Acid",
      img:"",
      cas:"141-82-2",
      formula:['C<sub>3</sub>H<sub>4</sub>O<sub>4</sub>'],
      // formula:"C3H4O4",
      othernames:"Propanedioic acid",
    },
    {
      id: 102,
      title: "Malononitrile",
      img:"",
      cas:"109-77-3",
      formula:['C<sub>3</sub>H<sub>2</sub>N<sub>2</sub>',' or ', 'NCCH<sub>2</sub>CN', ' or ', 'CH<sub>2</sub>(CN)<sub>2</sub>'],
      // formula:"C3H2N2 or NCCH2CN or CH2(CN)2",
      othernames:"Propanedinitrile",
    },
    {
      id: 103,
      title: "Melamine",
      img:"",
      cas:"108-78-1",
      formula:['C<sub>3</sub>H<sub>6</sub>N<sub>6</sub>',' or ','C<sub>3</sub>3(NH<sub>2</sub>)<sub>3</sub>'],
      // formula:"C3H6N6 or C3N3(NH2)3",
      othernames:"1,3,5-Triazine-2,4,6-triamine",
    },
    {
      id: 104,
      title: "Meta Cresol",
      img:"",
      cas:"108-39-4",
      formula:['C<sub>7</sub>H<sub>8</sub>O', 'CH<sub>3</sub>C<sub>6</sub>H<sub>4</sub>OH'],
      // formula:"C7H8O or CH3C6H4OH",
      othernames:"3-methylphenol",
    },
    {
      id: 105,
      title: "Metha Acrylic Acid",
      img:"",
      cas:"79-41-4",
      formula:['C<sub>4</sub>H<sub>6</sub>O<sub>2</sub>'],
      // formula:"C4H6O2",
      othernames:"2-Methylacrylic acid",
    },
    {
      id: 106,
      title: "Methane Sulphonic Acid",
      img:"",
      cas:"75-75-2",
      formula:['CH<sub>4</sub>O<sub>3</sub>S'],
      // formula:"CH4O3S",
      othernames:"Methylsulfonic acid",
    },
    {
      id: 107,
      title: "Methane Sulphonyl Chloride",
      img:"",
      cas:"124-63-0",
      formula:['CH<sub>3</sub>CLO<sub>2</sub>S'],
      // formula:"CH3ClO2S",
      othernames:"Mesyl chlorid",
    },
    {
      id: 108,
      title: "Methyl Aceto Acetate",
      img:"",
      cas:"105-45-3",
      formula:['C<sub>5</sub>H<sub>8</sub>O<sub>3</sub>'],
      // formula:"C5H8O3",
      othernames:"Methyl 3-oxobutanoate",
    },
    {
      id: 109,
      title: "Methyl Chloro Formate",
      img:"",
      cas:"79-22-1",
      formula:['C<sub>2</sub>H<sub>3</sub>CLO<sub>2</sub>', 'CH<sub>3</sub>OCOCL'],
      // formula:"C2H3ClO2 or CH3OCOCl",
      othernames:"Methyl chlorocarbonate",
    },
    {
      id: 110,
      title: "Methyl Cyano Acetate",
      img:"",
      cas:"105-34-0",
      formula:['C<sub>4</sub>H<sub>5</sub>NO<sub>2</sub>'],
      // formula:"C4H5NO2",
      othernames:"Methyl 2-cyanoacetate",
    },
    {
      id: 111,
      title: "Methyl Cyclohexane",
      img:"",
      cas:"101-68-8",
      formula:['C<sub>15</sub>H<sub>10</sub>N<sub>2</sub>O<sub>2</sub>'],
      // formula:"C15H10N2O2",
      othernames:"Cyclohexylmethane",
    },
    {
      id: 112,
      title: "Methylene Diphenyl Diisocyante",
      img:"",
      cas:"108-87-2",
      formula:['C<sub>7</sub>H<sub>14</sub>', ' or ' ,'C<sub>H</sub>11<sub>CH<sub>3</sub>'],
      // formula:"C7H14 or C6H11CH3",
      othernames:"1,1'-Methylenebis(4-isocyanatobenzene);",
    },
    {
      id: 113,
      title: "Methyl Methacrylate",
      img:"",
      cas:"80-62-6",
      formula:['C<sub>5</sub>H<sub>8</sub>O<sub>2</sub>'],
      // formula:"C5H8O2",
      othernames:"Methyl 2-methylprop-2-enoate",
    },
    {
      id: 114,
      title: "Monoethylamine",
      img:"",
      cas:"75-04-7",
      formula:['CH<sub>3</sub>CH<sub>2</sub>NH<sub>2</sub>'],
      // formula:"CH3CH2NH2",
      othernames:"Aminoethane",
    },
    {
      id: 115,
      title: "Mono Chloro Benzene",
      img:"",
      cas:"108-90-7",
      formula:['C<sub>6</sub>H<sub>5</sub>CL'],
      // formula:"C6H5Cl",
      othernames:"Chlorobenzene",
    },
    {
      id: 116,
      title: "Mono Methylamine",
      img:"",
      cas:"74-89-5",
      formula:['CH<sub>5</sub>N',' or ','CH<sub>3</sub>NH<sub>2</sub>'],
      // formula:"CH5N or CH3NH2",
      othernames:"Methanamine",
    },
    {
      id: 117,
      title: "Mono Ethylene Glycol",
      img:"",
      cas:"107-21-1",
      formula:['C<sub>2</sub>H<sub>6</sub>O<sub>2</sub>'],
      // formula:"C2H6O2",
      othernames:"Ethylene Glycol (EG)",
    },
    {
      id: 118,
      title: "Mono Iso Propylamine 70%",
      cas:"75-31-0",
      formula:['C<sub>3</sub>H<sub>9</sub>N', ' or ','(CH<sub>3</sub>)<sub>2</sub>CHNH<sub>2</sub>'],
      // formula:"C3H9N or (CH3)2CHNH2",
      othernames:"Isopropylamine; 2-Propanamine",
    },
    {
      id: 119,
      title: "Mono Iso Propylamine 99%",
      img:"",
      cas:"75-31-0",
      formula:['C<sub>3</sub>H<sub>9</sub>N', ' or ','(CH<sub>3</sub>)<sub>2</sub>CHNH<sub>2</sub>'],
      // formula:"C3H9N or (CH3)2CHNH2",
      othernames:"Isopropylamine;",
    },
    {
      id: 120,
      title: "Morpholine",
      img:"",
      cas:"110-91-8",
      formula:['H<sub>2</sub>SO<sub>4</sub>', 'CO<sub>2</sub>'],
      // formula:"C4H9NO",
      othernames:"",
    },
    {
      id: 121,
      title: "MP Diol Glycol",
      img:"",
      cas:"2163-42-0",
      formula:['C<sub>4</sub>H<sub>10</sub>O<sub>2</sub>'],
      // formula:"C4H10O2",
      othernames:"1-Oxa-4-azacyclohexane",
    },
    {
      id: 122,
      title: "N- Ethyl Piperazine",
      img:"",
      cas:"5308-25-8",
      formula:['C<sub>6</sub>H<sub>14</sub>N<sub>2</sub>'],
      // formula:"C6H14N2",
      othernames:"2-Methyl-1,3-propanediol",
    },
    {
      id: 123,
      title: "N- Butyric Acid",
      img:"",
      cas:"107-92-6",
      formula:['H<sub>2</sub>SO<sub>4</sub>', 'CO<sub>2</sub>'],
      // formula:"C4H8O2",
      othernames:"",
    },
    {
      id: 124,
      title: "N- Butyl Methacrylate",
      img:"",
      cas:"97-88-1",
      formula:['C<sub>8</sub>H<sub>14</sub>O<sub>2</sub>'],
      // formula:"C8H14O2",
      othernames:"2-Propenoic acid",
    },
    {
      id: 125,
      title: "N- Butanol",
      img:"",
      cas:"71-36-3",
      formula:['C<sub>4</sub>H<sub>10</sub>O'],
      // formula:"C4H10O",
      othernames:"Butan-1-ol;",
    },
    {
      id: 126,
      title: "N- Butyraldehyde",
      img:"",
      cas:"123-72-8",
      formula:['C<sub>4</sub>H<sub>8</sub>O'],
      // formula:"C4H8O",
      othernames:"Butyraldehyde;",
    },
    {
      id: 127,
      title: "N- Methyl Piperazine",
      img:"",
      cas:"109-01-3",
      formula:['C<sub>5</sub>H<sub>12</sub>N<sub>2</sub>'],
      // formula:"C5H12N2",
      othernames:"1-Methylpiperazine",
    },
    {
      id: 128,
      title: "Napthalene Crude",
      img:"",
      cas:"91-20-3",
      formula:['C<sub>10</sub>H<sub>8</sub>'],
      // formula:"C10H8",
      othernames:"Camphor tar",
    },
    {
      id: 129,
      title: "Napthalene Refined",
      img:"",
      cas:"91-20-3",
      formula:['C<sub>10</sub>H<sub>8</sub>'],
      // formula:"C10H8",
      othernames:"Naphthalin",
    },
    {
      id: 130,
      title: "Neo Pentyl Glycol",
      img:"",
      cas:"126-30-7",
      formula:['C<sub>5</sub>H<sub>12</sub>O<sub>2</sub>'],
      // formula:"C5H12O2",
      othernames:"2,2-Dimethylpropane-1,3",
    },
    {
      id: 131,
      title: "Nitromethane",
      img:"",
      cas:"75-52-5",
      formula:['CH<sub>3</sub>NO<sub>2</sub>'],
      // formula:"CH3NO2",
      othernames:"Nitrocarbol",
    },
    {
      id: 132,
      title: "Nonyl Phenol",
      img:"",
      cas:"104-40-5",
      formula:['C<sub>15</sub>H<sub>24</sub>O'],
      // formula:"C15H24O",
      othernames:"4-(2,4-dimethylheptan-3-yl)phenol",
    },
    {
      id: 133,
      title: "Nonyl Phenol Ethoxylate",
      img:"",
      cas:"20427-84-3",
      formula:['C<sub>19</sub>H<sub>32</sub>O<sub>3</sub>'],
      // formula:"C19H32O3",
      othernames:"Nonoxynol-3",
    },
    {
      id: 134,
      title: "Oxone PS - 16",
      img:"",
      cas:"37222-66-5",
      formula:['H<sub>3</sub>k<sub>5</sub>o<sub>18</sub>s<sub>4</sub>'],
      // formula:" H3K5O18S4",
      othernames:"Potassium Peroxomonosulfate",
    },
    {
      id: 135,
      title: "Para Tertiary Butyl Phenol",
      img:"",
      cas:"98-54-4",
      formula:['C<sub>10</sub>H<sub>14</sub>O', ' or' ,'HOC<sub>6</sub>H<sub>4</sub>C(<sub>CH</sub>3)<sub>3</sub>'],
      // formula:"C10H14O or HOC6H4C(CH3)3",
      othernames:"4-(tert-Butyl)phenol; PTBP",
    },
    {
      id: 136,
      title: "Para Tertiary Octyl Phenol",
      img:"",
      cas:"140-66-9",
      formula:['C<sub>14</sub>H<sub>22</sub>O'],
      // formula:"C14H22O",
      othernames:"4-tert-Octylphenol",
    },
    {
      id: 137,
      title: "Para Toluene Sulfonyl Chloride",
      img:"",
      cas:"98-59-9",
      formula:['C<sub>7</sub>H<sub>7</sub>CLO<sub>2</sub>S' ],
      // formula:"C7H7ClO2S",
      othernames:"p-Tosyl chloride",
    },
    {
      id: 138,
      title: "Paraformaldehyde 91%",
      img:"",
      cas:"30525-89-4",
      formula:['(CH<sub>2</sub>O)N'],
      // formula:"(CH2O)n",
      othernames:"Polyoxymethylene",
    },
    {
      id: 139,
      title: "Paraformaldehyde 96%",
      img:"",
      cas:"30525-89-4",
      formula:['(CH<sub>2</sub>O)N'],
      // formula:"(CH2O)n",
      othernames:"Polyoxymethylene",
    },
    {
      id: 140,
      title: "Pentaerythritol 98%",
      img:"",
      cas:"30525-89-4",
      formula:['(CH<sub>2</sub>O)N'],
      // formula:"(CH2O)n",
      othernames:"Monopentaerythrito",
    },
    {
      id: 141,
      title: "Perchloroethylene",
      img:"",
      cas:"127-18-4",
      formula:['C<sub>2</sub>CL<sub>4</sub>'],
      // formula:" C2Cl4",
      othernames:"Tetrachloroethene",
    },
    {
      id: 142,
      title: "Phosphoric Acid (Food Grade)",
      img:"",
      cas:"7664-38-2",
      formula:['H<sub>3</sub>PO<sub>4</sub>',' or ' , 'H<sub>3</sub>O<sub>4</sub>P'],
      // formula:"H3PO4 or H3O4P",
      othernames:"Orthophosphoric acid",
    },
    {
      id: 143,
      title: "Phosphoric Acid (Technical)",
      img:"",
      cas:"7664-38-2",
      formula:['H<sub>2</sub>SO<sub>4</sub>', 'CO<sub>2</sub>'],
      // formula:" H3PO4 or H3O4P",
      othernames:"",
    },
    {
      id: 144,
      title: "Phosphorus Oxychloride",
      img:"",
      cas:"10025-87-3",
      formula:['POCL<sub>3</sub>'],
      // formula:" POCl3",
      othernames:"Orthophosphoric acid",
    },
    {
      id: 145,
      title: "Phosphorus Pentaoxide",
      img:"",
      cas:"1314-56-3",
      formula:['P<sub>4</sub>O<sub>10</sub>', ' or ', 'P<sub>2</sub>O<sub>5</sub>'],
      // formula:"P4O10 or P2O5",
      othernames:"Diphosphorus pentoxide;",
    },
    {
      id: 146,
      title: "Piperazine Anhydrous",
      img:"",
      cas:"110-85-0",
      formula:['C<sub>4</sub>H<sub>10</sub>N<sub>2</sub>'],
      // formula:"C4H10N2",
      othernames:"Hexahydropyrazine",
    },
    {
      id: 147,
      title: "Poly Vinyl Alcohol",
      img:"",
      cas:"9002-89-5",
      formula:[' C<sub>2</sub>H<sub>4</sub>O'],
      // formula:"C2H4O",
      othernames:"Vinyl alcoho",
    },
    {
      id: 148,
      title: "Polyethylene Glycol",
      img:"",
      cas:"25322-68-3",
      formula:['C<sub>69</sub>H<sub>140</sub>O<sub>35</sub>'],
      // formula:"C69H140O35",
      othernames:"Poly(oxyethylene)",
    },
    {
      id: 149,
      title: "Polypropylene Glycol 1000D",
      img:"",
      cas:"25322-69-4",
      formula:['C<sub>6</sub>H<sub>14</sub>O<sub>3</sub>'],
      // formula:"C6H14O3",
      othernames:"2-(2-hydroxypropoxy)propan-1-o",
    },
    {
      id: 150,
      title: "Polypropylene Glycol 2000D",
      img:"",
      cas:"25322-69-4",
      formula:['C<sub>6</sub>H<sub>14</sub>O<sub>3</sub>'],
      // formula:"C6H14O3",
      othernames:"2-(2-hydroxypropoxy)propan-1-ol",
    },
    {
      id: 151,
      title: "Potassium Bi Carbonate",
      img:"",
      cas:"298-14-6",
      formula:['KHCO<sub>3</sub>'],
      // formula:"KHCO3",
      othernames:"Potassium hydrogen carbonate",
    },
    {
      id: 152,
      title: "Potassium Carbonate (Granual)",
      img:"",
      cas:"584-08-7",
      formula:['H<sub>2</sub>SO<sub>4</sub>', 'CO<sub>2</sub>'],
      // formula:"K2CO3",
      othernames:"",
    },
    // {
    //   id: 152,
    //   title: "Potassium Carbonate (Powder)",
    //   img:"",
    //   cas:"584-08-7 ",
    //   formula:['H<sub>2</sub>SO<sub>4</sub>', 'CO<sub>2</sub>'],
    //   // formula:" K2CO3",
    //   othernames:"",
    // },  
    {
      id: 153,
      title: "Potassium Permanganate",
      img:"",
      cas:"7722-64-7",
      formula:['K<sub>2</sub>CO<sub>3</sub>'],
      // formula:" K2CO3",
      othernames:"Potassium manganate(VII);",
    },  
    {
      id: 154,
      title: "Phenyl Chloro Formate",
      img:"",
      cas:"1885-14-9",
      formula:['C<sub>7</sub>H<sub>5</sub>CLO<sub>2</sub>', ' or ' ,'C<sub>6</sub>H<sub>5</sub>COCL'],
      // formula:"C7H5ClO2 or C6H5OCOCl",
      othernames:"Phenyl carbonochloridate;",
    },
    {
      id: 155,
      title: "Propionaldehyde",
      img:"",
      cas:"123-38-6",
      formula:['C<sub>3</sub>H<sub>6</sub>O',' or ','CH<sub>3</sub>CH<sub>2</sub>CHO<sub>8</sub>'],
      // formula:"C3H6O or CH3CH2CHO8",
      othernames:"Methylacetaldehyde",
    },
    {
      id: 156,
      title: "Propionic Acid",
      img:"",
      cas:"79-09-4",
      formula:['C<sub>3</sub>H<sub>6</sub>O<sub>2</sub>'],
      // formula:"C3H6O2",
      othernames:"Propanoic acid",
    },
    {
      id: 157,
      title: "Propionic Anhydride",
      img:"",
      cas:"123-62-6",
      formula:['H<sub>2</sub>SO<sub>4</sub>', 'CO<sub>2</sub>'],
      // formula:" C6H10O3 or (CH3CH2CO)2O",
      othernames:"",
    },
    {
      id: 158,
      title: "Propargyl Alcohol",
      img:"",
      cas:"107-19-7",
      formula:['C<sub>3</sub>H<sub>4</sub>O'],
      // formula:"C3H4O or CHCCH2OH",
      othernames:"2-Propynyl alcohol",
    },
    {
      id: 159,
      title: "Propylene Glycol (Technical)",
      img:"",
      cas:"57-55-6",
      formula:['C<sub>3</sub>H<sub>8</sub>O<sub>2</sub>'],
      // formula:"C3H8O2",
      othernames:"Propane-1,2-diol;",
    },
    {
      id: 160,
      title: "Propylene Glycol (USP)",
      img:"",
      cas:"57-55-6",
      formula:['C<sub>3</sub>H<sub>8</sub>O<sub>2</sub>'],
      // formula:"C3H8O2",
      othernames:"Propane-1,2-diol",
    },
    {
      id: 161,
      title: "Phthalic Anhydride",
      img:"",
      cas:"85-44-9",
      formula:['C<sub>8</sub>H<sub>4</sub>O<sub>3</sub>', 'C<sub>6</sub>H<sub>4</sub>(CO)<sub>2</sub>O'],
      // formula:"C8H4O3 or C6H4(CO)2O",
      othernames:"Isobenzofuran-1,3-dione",
    },
    {
      id: 162,
      title: "Pyridine",
      img:"",
      cas:"110-86-1",
      formula:['C<sub>5</sub>H<sub>5</sub>N'],
      // formula:" C5H5N",
      othernames:"Azabenzen",
    },
    
    {
      id: 163,
      title: "Pyrrolidine",
      img:"",
      cas:"123-75-1",
      formula:['C<sub>4</sub>H<sub>9</sub>N'],
      // formula:"C4H9N",
      othernames:"Azacyclopentane",
    },
    
    {
      id: 164,
      title: "Resorcinol",
      img:"",
      cas:"108-46-3",
      formula:['C<sub>6</sub>H<sub>6</sub>O<sub>2</sub>'],
      // formula:"C6H6O2",
      othernames:"Benzene-1,3-diol;",
    },
    {
      id: 165,
      title: "Soda Ash",
      img:"",
      cas:"497-19-8",
      formula:['NA<sub>2</sub>CO<sub>3</sub>'],
      // formula:"Na2CO3",
      othernames:"Sodium carbonate",
    },
    {
      id: 166,
      title: "Sodium Borohydride (Granual)",
      img:"",
      cas:"16940-66-2",
      formula:['NABH<sub>4</sub>', ' or ','BH<sub>4</sub>NA'],
      // formula:"NaBH4 or BH4Na",
      othernames:"Sodium tetrahydridoborate",
    },
    
    {
      id: 167,
      title: "Sodium Borohydride (Powder)",
      img:"",
      cas:"16940-66-2",
      formula:['  NABH<sub>4</sub>',  ' ', 'BH<sub>4</sub>NA'],
      // formula:" NaBH4 or BH4Na",
      othernames:"Sodium tetrahydridoborate",
    },
    {
      id: 168,
      title: "Sodium Cyanide",
      img:"",
      cas:"143-33-9",
      formula:['NACN', ' or ','CNNA'],
      // formula:"NaCN or CNNa",
      othernames:"Cyanogran",
    },
    {
      id: 169,
      title: "Sodium Gluconate",
      img:"",
      cas:"527-07-1",
      formula:['C<sub>6</sub>H<sub>11</sub>NAO<sub>7</sub>'],
      // formula:" C6H11NaO7",
      othernames:"Gluconic acid sodium salt",
    },
    {
      id: 170,
      title: "Sodium Gluconate",
      img:"",
      cas:"527-07-1",
      formula:['H<sub>2</sub>SO<sub>4</sub>', 'CO<sub>2</sub>'],
      // formula:"C6H11NaO7",
      othernames:"",
    },
    {
      id: 171,
      title: "Sodium Ligno Sulphonate",
      img:"",
      cas:"8061-51-6",
      formula:['C<sub>20</sub>H<sub>24</sub>NA<sub>2</sub>0<sub>10</sub>S<sub>2</sub>'],
      // formula:" C20H24Na2O10S2",
      othernames:"Sodium lignin sulfonate",
    },
    {
      id: 172,
      title: "Sodium Metabisulphite",
      img:"",
      cas:"7681-57-4",
      formula:['NA<sub>2</sub>S<sub>2</sub>O<sub>5</sub>'],
      // formula:" Na2S2O5",
      othernames:"Sodium pyrosulfite",
    },
    {
      id: 173,
      title: "Sodium Metal",
      img:"",
      cas:"7440-23-5",
      formula:['NA'],
      // formula:"Na",
      othernames:"Sodium",
    },
    {
      id: 174,
      title: "Sodium Methoxide Powder",
      img:"",
      cas:"124-41-4",
      formula:['CH<sub>3</sub>ONA', ' or ' , 'CH<sub>3</sub>NAO'],
      // formula:"CH3ONa or CH3NaO",
      othernames:"Sodium methanolate",
    },
    {
      id: 175,
      title: "Sodium Nitrate",
      img:"",
      cas:"7631-99-4",
      formula:['NANO<sub>3</sub>', ' or ', 'NNAO<sub>3</sub>'],
      // formula:" NaNO3 or NNaO3",
      othernames:"Nitratine",
    },
    {
      id: 176,
      title: "Sodium Nitrite",
      img:"",
      cas:"7632-00-0",
      formula:['NANO<sub>2</sub>', ' or ' ,  'NNAO<sub>2</sub>'],
      // formula:" NaNO2 or NNaO2",
      othernames:"Nitrous acid",
    },
    
    {
      id: 177,
      title: "Sodium Thiocyanate",
      img:"",
      cas:"540-72-7",
      formula:['NASCN', ' or ' ,'CNNAS'],
      // formula:"NaSCN or CNNaS",
      othernames:"Sodium rhodanide",
    },
    {
      id: 178,
      title: "Sodium Tri Polyphosphate",
      img:"",
      cas:"7758-29-4",
      formula:['NA<sub>5</sub>O<sub>10</sub>P<sub>3</sub>'],
      // formula:"Na5O10P3",
      othernames:"Pentasodium triphosphate",
    },
    {
      id: 179,
      title: "Tertiary Butanol",
      img:"",
      cas:"75-65-0",
      formula:['H<sub>2</sub>SO<sub>4</sub>', 'CO<sub>2</sub>'],
      // formula:":C4H10O or (CH3)3COH",
      othernames:"",
    },
    
    {
      id: 180,
      title: "Tertiary Butylamine",
      img:"",
      cas:"75-64-9",
      formula:['C<sub>4</sub>H<sub>10</sub>O', ' or '  , '(CH<sub>3</sub>)<sub>3</sub>COH'],
      // formula:":C4H10O or (CH3)3COH",
      othernames:"t-Butyl alcohol",
    },
    {
      id: 181,
      title: "Tertiary Butylamine",
      img:"",
      cas:"75-64-9",
      formula:['C<sub>4</sub>H<sub>10</sub>O', 'or','(CH<sub>3</sub>)<sub>3</sub>COH'],
      // formula:"C4H10O or (CH3)3COH",
      othernames:"2-Methylpropan-2-amine",
    },
    {
      id: 182,
      title: "Thiophenol",
      img:"",
      cas:"108-98-5",
      formula:['C<sub>6</sub>H<sub>6</sub>S',' or ', 'C<sub>6</sub>H<sub>5</sub>SH'],
      // formula:"C6H6S or C6H5SH",
      othernames:"Benzenethiol",
    },
    {
      id: 183,
      title: "Thiourea",
      img:"",
      cas:"62-56-6",
      formula:['CH<sub>4</sub>N<sub>2</sub>S',  ' or '  , 'H<sub>2</sub>NCSNH<sub>2</sub>'],
      // formula:" CH4N2S or H2NCSNH2",
      othernames:"Thiocarbamide;",
    },
    
    {
      id: 184,
      title: "Toluene Di Isocyanate",
      img:"",
      cas:"584-84-9",
      formula:['C<sub>9</sub>H<sub>6</sub>N<sub>2</sub>O<sub>2</sub>',  ' or ','CH<sub>3</sub>C<sub>6</sub>H<sub>3</sub>(NO)<sub>2</sub>'],
      // formula:"C9H6N2O2 or CH3C6H3(NCO)2",
      othernames:" Methyl phenylene diisocyanate",
    },
    
    {
      id: 185,
      title: "Tri Ethyl Phosphate",
      img:"",
      cas:"78-40-0",
      formula:['C<sub>6</sub>H<sub>15</sub>O<sub>4</sub>P', ' or ', '(C<sub>2</sub>H<sub>5</sub>)<sub>3</sub>PO<sub>4</sub>'],
      // formula:"C6H15O4P or (C2H5)3PO4",
      othernames:"Triethoxyphosphine oxide;",
    },
    
    {
      id: 186,
      title: "Tri Ethyl Amine",
      img:"",
      cas:"121-44-8",
      formula:['C<sub>6</sub>SH<sub>15</sub>N', ' or ','(C<sub>2</sub>H<sub>5</sub>)<sub>3</sub>N'],
      // formula:"C6H15N or (C2H5)3N",
      othernames:"N,N-Diethylethanamine",
    },
    {
      id: 187,
      title: "Tri Ethylene Pentamine",
      img:"",
      cas:"112-57-2",
      formula:['C<sub>8</sub>H<sub>23</sub>N<sub>5</sub>'],
      // formula:": C8H23N5",
      othernames:" 3,6,9-Triazaundecamethylenediamine",
    },
    {
      id: 188,
      title: "Tri Mellitic Anhydride",
      img:"",
      cas:"552-30-7",
      formula:['C<sub>9</sub>H<sub>4</sub>O<sub>5</sub>'],
      // formula:" C9H4O5",
      othernames:"1,3-Dioxo-1,3-dihydroisobenzofuran-5-carboxylic acid;",
    },
    {
      id: 189,
      title: "Tri Methyl Ortho Acetate",
      img:"",
      cas:"1445-45-0 ",
      formula:['C<sub>5</sub>H<sub>12</sub>O<sub>3</sub>'],
      // formula:"C5H12O3",
      othernames:"1,1,1-Trimethoxyethane",
    },
    {
      id: 190,
      title: "Tri Methyl Ortho Formate",
      img:"",
      cas:"112-57-2 ",
      formula:['C<sub>8</sub>H<sub>23</sub>N<sub>5</sub>'],
      // formula:"C8H23N5",
      othernames:"; 3,6,9-Triazaundecamethylenediamine",
    },
    
    {
      id: 191,
      title: "Tri Methylol Propane",
      img:"",
      cas:"112-57-2 ",
      formula:['C<sub>8</sub>H<sub>23</sub>N<sub>5</sub>'],
      // formula:"C8H23N5",
      othernames:"1,4,7,10,13-Pentaazatridecane;",
    },
    
    {
      id: 192,
      title: "Tri N Butylamine",
      img:"",
      cas:"102-82-9 ",
      formula:['C<sub>12</sub>H<sub>27</sub>N'],
      // formula:"C12H27N",
      othernames:"N,N-dibutyl-1-butaanamine;",
    },
    {
      id: 193,
      title: "Triethanolamine 85% & 99%",
      img:"",
      cas:"102-71-6 ",
      formula:['C<sub>6</sub>H<sub>15</sub>NO<sub>3</sub>'],
      // formula:"C6H15NO3",
      othernames:"Trolamine; 2,2',2''-Nitrilotriethanol",
    },
    {
      id: 194,
      title: "Triethylene Tetramine",
      img:"",
      cas:"112-24-3",
      formula:['C<sub>6</sub>H<sub>18</sub>N<sub>4</sub>'],
      // formula:"C6H18N4",
      othernames:"N,N'-Bis(2-aminoethyl)ethane-1,2-diamine",
    },
    
    {
      id: 195,
      title: "Urea (Technical Grade)",
      img:"",
      cas:"57-13-6 ",
      formula:['CH<sub>4</sub>N<sub>2</sub>O',' or ', 'NH<sub>2</sub>CONH<sub>2</sub>'],
      // formula:"CH4N2O or NH2CONH2",
      othernames:"Carbonyldiamine",
    },
    
    
  ];
  export const specialityChemicals = [
    {
      id: 1,
      title: "Di Methyl Amino Pyridine",
      img:"./assets/images/Products-all-img/chemicals/specialityChemicals/sc-1.webp",
      cas:"1122-58-3",
      formula:['C<sub>7</sub>H<sub>10</sub>N<sub>2</sub>'],
      // formula:"C7H10N2",
      othernames:"4-Dimethylaminopyridine",
    },
    {
      id: 2,
      title: "Piperidine",
      img:"./assets/images/Products-all-img/chemicals/specialityChemicals/sc-2.webp",
      cas:"110-89-4",
      formula:['C<sub>5</sub>H<sub>11</sub>N'],
      // formula:" C5H11N",
      othernames:"Hexahydropyridine",
    },
  ];
