export const polymers = [
    {
      id: 1,
      title: "Ethylene Vinyl Acetate (EVA)",
      img: "https://img.freepik.com/free-vector/colorful-realistic-science-background_52683-35755.jpg?w=1060&t=st=1695119643~exp=1695120243~hmac=dd0ff0382ba2bafdc7cff751f8b13f8b14cf8318437e07b67d14106aa31e79a2",
      cas:"24937-78-8",
      formula:"(C2H4)n(C4H6O2)m",
      othernames:"",
    },
    {
      id: 2,
      title: "Polyethelyne Terephthalate (PET Resin)",
      img: "https://img.freepik.com/free-photo/researching-laboratory_1384-138.jpg?w=1060&t=st=1695119686~exp=1695120286~hmac=a9fd6ac335eebfb1a33b1096cf671b35e3d34a8d02029dc659ca0620b4a4c298",
      cas:"25038-59-9",
      formula:"(C10H8O4)n",
      othernames:"",

    },
    {
      id: 3,
      title: "Polyvinyl Chloride Resin (PVC Resin)",
      img:"https://img.freepik.com/premium-photo/abstract-molecular-structures-unveiled-exploring-scientific-essence-3d-dna-molecules-biotechnology_938416-1621.jpg?w=1380",
      cas:"9002-86-2",
      formula:"(C2H3Cl)n",
      othernames:"",
    },
    {
    id: 4,
      title: "Ethylene Vinyl Acetate (EVA)",
      img: "https://img.freepik.com/free-vector/colorful-realistic-science-background_52683-35755.jpg?w=1060&t=st=1695119643~exp=1695120243~hmac=dd0ff0382ba2bafdc7cff751f8b13f8b14cf8318437e07b67d14106aa31e79a2",
      cas:"24937-78-8",
      formula:"(C2H4)n(C4H6O2)m",
      othernames:"",
    },
    {
      id: 5,
      title: "Polyethelyne Terephthalate (PET Resin)",
      img: "https://img.freepik.com/free-photo/researching-laboratory_1384-138.jpg?w=1060&t=st=1695119686~exp=1695120286~hmac=a9fd6ac335eebfb1a33b1096cf671b35e3d34a8d02029dc659ca0620b4a4c298",
      cas:"25038-59-9",
      formula:"(C10H8O4)n",
      othernames:"",

    },
    {
      id: 6,
      title: "Polyvinyl Chloride Resin (PVC Resin)",
      img:"https://img.freepik.com/premium-photo/abstract-molecular-structures-unveiled-exploring-scientific-essence-3d-dna-molecules-biotechnology_938416-1621.jpg?w=1380",
      cas:"9002-86-2",
      formula:"(C2H3Cl)n",
      othernames:"",
    },
  ];
  export const solvents = [
      {
        id: 1,
        title: "Acetone",
        img:"https://img.freepik.com/free-photo/experiments-chemistry-lab-conducting-experiment-laboratory_155003-1401.jpg?w=1060&t=st=1695298527~exp=1695299127~hmac=f2a732bb34a8eae9134fde508363fff68fd496fb8f56e8b2ba434aa72a192707",
        cas:"67-64-1",
        formula:"C3H6O or CH3COCH3",
        othernames:"",
      },
      {
        id: 2,
        title: "Acetic Acid",
        img:"https://img.freepik.com/free-photo/closeup-shot-different-flasks-with-colorful-liquids-white-surface-lab_181624-43901.jpg?w=1060&t=st=1695298562~exp=1695299162~hmac=5f30205d0854b78d8c9bd9af87eb2a505b9e922df306168b5b7214c03e60c579",
        cas:"64-19-7",
        formula:"C2H4O2 or CH3COOH",
        othernames:"",
      },
      {
        id: 3,
        title: "Acrylonitrile",
        img:"https://img.freepik.com/free-photo/close-up-view-science-concept-with-copy-space_23-2148623726.jpg?w=1380&t=st=1695298585~exp=1695299185~hmac=05b71893a516ce28ab34bf93c0c5d98aa48360fe892532b3272b991b84e7b85d",
        cas:"107-13-1",
        formula:"C3H3N or H2C(CH)CN",
        othernames:"",
      },
      {
        id: 4,
        title: "Butyl Acetate",
        img:"https://img.freepik.com/free-photo/molecules-connect-scientific-discovery-symbolizing-progress-generated-by-ai_188544-16444.jpg?t=st=1695298606~exp=1695302206~hmac=e7aab54dcbb2eebf242c6634d376910c050f614e505c28565ed89a22f568813f&w=1380",
        cas:"79-06-1",
        formula:"C6H12O2 or CH3COO(CH2)3CH3",
        othernames:"",
      },

      {
        id: 5,
        title: "Butyl Glycol",
        img:"https://img.freepik.com/free-photo/modern-laboratory-interior_1098-17082.jpg?w=1060&t=st=1695298632~exp=1695299232~hmac=bb69b0967065101eea7072c7a052648a5b6a924a79f33543bcf82d217d6f3d3d",
        cas:"111-76-2",
        formula:"C6H14O2",
        othernames:"",
      },

      {
        id: 6,
        title: "C -IX",
        img:"https://img.freepik.com/premium-photo/collection-medical-flasksscience-glass-flask-blue-chemistry-laboratoryconcept-medicine_666266-26.jpg?w=1060",
        cas:"64742-95-6",
        formula:"C9H12",
        othernames:"",
      },
      {
        id: 7,
        title: "Cyclohexanone",
        img:"",
        cas:"108-94-1",
        formula:"C6H10O",
        othernames:"",
      },
      {
        id: 8,
        title: "Ethylene Di Chloride",
        img:"",
        cas:"107-06-2",
        formula:"ClCH2CH2Cl or C2H4Cl2",
        othernames:"",
      },
      {
        id: 9,
        title: "Iso Propyl Alcohol",
        img:"",
        cas:"67-63-0",
        formula:"C3H8O",
        othernames:"",
      },
      {
        id: 10,
        title: "Iso Butanol",
        img:"",
        cas:"78-83-1",
        formula:"C4H10O or (CH3)2CHCH2OH",
        othernames:"",
      },
      {
        id: 11,
        title: "Methanol",
        img:"",
        cas:"67-56-1",
        formula:"CH4O or CH3OH",
        othernames:"",
      },
      {
        id: 12,
        title: "Methylene Di Chloride",
        img:"",
        cas:"75-09-2",
        formula:"CH2Cl2",
        othernames:"",
      },
      {
        id: 13,
        title: "Methyl Ethyl Ketone",
        img:"",
        cas:"78-93-3",
        formula:"C4H8O",
        othernames:"",
      },
      {
        id: 14,
        title: "Methy Iso Butyl Ketone",
        img:"",
        cas:"108-10-1",
        formula:"C6H12O",
        othernames:"",
      },
      {
        id: 15,
        title: "N Butanol",
        img:"",
        cas:"71-36-3",
        formula:"C4H10O",
        othernames:"",
      },
      {
        id: 16,
        title:"N - Hexane",
        img:"",
        cas:"110-54-3",
        formula:"C6H14",
        othernames:"",
      },
      {
        id: 17,
        title: "Phenol",
        img:"",
        cas:"108-95-2",
        formula:"C6H6O or C6H5OH",
        othernames:"",
      },
      {
        id: 18,
        title: "Toluene",
        img:"",
        cas:"108-88-3",
        formula:"C6H5CH3 or C7H",
        othernames:"",
      },
      {
        id: 19,
        title: "Vinyl Acetate Monomer",
        img:"",
        cas:"108-05-4",
        formula:"C4H6O2",
        othernames:"",
      },
      {
        id: 20,
        title: "Xylene (Mix)",
        img:"",
        cas:"1330-20-7",
        formula:" C24H30",
        othernames:"",
      },
      {
        id: 21,
        title: "Xylene (Ortho)",
        img:"",
        cas:"95-47-6",
        formula:"C6H4(CH3)2 or C8H10",
        othernames:"",
      },
      {
        id: 22,
        title: "Acetone",
        img:"",
        cas:"67-64-1",
        formula:"(CH3)2CO",
        othernames:"",
      },
      {
        id: 23,
        title: "Acetic Acid",
        img:"",
        cas:"64-19-7",
        formula:"C2H4O2",
        othernames:"",
      },
      {
        id: 24,
        title: "Acrylonitrile",
        img:"",
        cas:"107-13-1",
        formula:"CH2CHCN",
        othernames:"",
      },
      {
        id: 25,
        title: "Acetonitrile",
        img:"",
        cas:"75-05-8",
        formula:"C2H3N",
        othernames:"",
      },
      {
        id: 26,
        title: "Butyl Acetate",
        img:"",
        cas:"123-86-4",
        formula:"C6H12O2 or CH3COO(CH2)3CH3",
        othernames:"",
      },
      {
        id: 27,
        title: "Butyl Acrylate",
        img:"",
        cas:"141-32-2",
        formula:" C7H12O2",
        othernames:"",
      },
      {
        id: 28,
        title: "Butyl Carbitol",
        img:"",
        cas:"112-34-5",
        formula:"C8H18O3",
        othernames:"",
      },
      {
        id: 29,
        title: "Butyl Carbitol Acetate",
        img:"",
        cas:"111-76-2",
        formula:"C10H20O4",
        othernames:"",
      },
      {
        id: 30,
        title: "Butyl Glycol/ Cellosolve",
        img:"",
        cas:"111-76-2",
        formula:"C6H14O2",
        othernames:"",
      },
      {
        id: 31,
        title: "Butyl Cellosolve Acetate",
        img:"",
        cas:"112-07-2",
        formula:"C8H16O3",
        othernames:"",
      },
      {
        id: 32,
        title: "Chloroform",
        img:"",
        cas:"67-66-3",
        formula:"CHCl3",
        othernames:"",
      },
      {
        id: 33,
        title: "Disopropyl Ether (DIPE)",
        img:"",
        cas:"108-20-3",
        formula:"C6H14O",
        othernames:"",
      },
      {
        id: 34,
        title: "Dimethyl Acetamide",
        img:"",
        cas:"127-19-5",
        formula:"C4H9NO or CH3CON(CH3)2",
        othernames:"",
      },
      {
        id: 35,
        title: "Dimethyl Formamide",
        img:"",
        cas:"68-12-2",
        formula:"C3H7NO or HCON(CH3)2",
        othernames:"",
      },
      {
        id: 36,
        title: "Dimethyl Sulfoxide",
        img:"",
        cas:"67-68-5",
        formula:"C2H6OS or (CH3)2SO",
        othernames:"",
      },
      {
        id: 37,
        title: "E Ethyl Acetate",
        img:"",
        cas:"141-78-6",
        formula:"C4H8O2 or CH3COOC2H5",
        othernames:"",
      },
      {
        id: 38,
        title: "Heptane",
        img:"",
        cas:"142-82-5",
        formula:"C7H16 or CH3(CH2)5CH3",
        othernames:"",
      },
      {
        id: 30,
        title: "Heptane S",
        img:"",
        cas:"142-82-5",
        formula:"C7H16",
        othernames:"",
      },
      {
        id: 40,
        title: "isobutanol",
        img:"",
        cas:"78-83-1",
        formula:"C4H10O or (CH3)2CHCH2OH",
        othernames:"",
      },
      {
        id: 41,
        title: "Methyl Ethyl Ketone",
        img:"",
        cas:"78-93-3",
        formula:"C4H8O",
        othernames:"",
      },
      {
        id: 42,
        title: "Isopropyl Alcohol",
        img:"",
        cas:"67-63-0",
        formula:"C3H8O",
        othernames:"",
      },
      {
        id: 43,
        title: "N Butanol",
        img:"",
        cas:"71-36-3",
        formula:"C4H10O",
        othernames:"",
      },
      {
        id: 44,
        title: "Isopropyl Acetate",
        img:"",
        cas:"108-21-4",
        formula:"C5H10O2",
        othernames:"",
      },
      {
        id: 45,
        title: "Methyl Ethyl Ketone",
        img:"",
        cas:"78-93-3",
        formula:"C4H10O",
        othernames:"",
      },
      {
        id: 46,
        title: "Methy Iso Butyl Ketone",
        img:"",
        cas:"108-10-1",
        formula:"C6H12O",
        othernames:"",
      },
      {
        id: 47,
        title: "Methyl Tertiary Butyl Ether (MTBE)",
        img:"",
        cas:"1634-04-4",
        formula:"C5H12O",
        othernames:"",
      },
      {
        id: 48,
        title: "Methylene Chloride",
        img:"",
        cas:"75-09-2",
        formula:"CH2Cl2",
        othernames:"",
      },
      {
        id: 49,
        title: "Monoglyme",
        img:"",
        cas:"110-71-4",
        formula:"C4H10O2",
        othernames:"",
      },
      {
        id: 50,
        title: "N - Methyl - 2 - Pyrrolidone (NMP)",
        img:"",
        cas:"872-50-4",
        formula:"C5H9NO",
        othernames:"",
      },
      {
        id: 51,
        title: "N - Pentane",
        img:"",
        cas:"109-66-0",
        formula:"C5H12",
        othernames:"",
      },
      {
        id: 52,
        title: "N - Propanol",
        img:"",
        cas:"71-23-8",
        formula:"C3H8O",
        othernames:"",
      },
      {
        id: 53,
        title: "N - Propyl Acetate",
        img:"",
        cas:"109-60-4",
        formula:"C5H10O2",
        othernames:"",
      },
      {
        id: 54,
        title: "N- Butanol",
        img:"",
        cas:"71-36-3",
        formula:"C4H10O",
        othernames:"",
      },
      {
        id: 55,
        title: "N - Hexane 99%",
        img:"",
        cas:"110-54-3",
        formula:"C6H14",
        othernames:"",
      },
      {
        id: 56,
        title: "N - Heptane",
        img:"",
        cas:"142-82-5",
        formula:"C7H16",
        othernames:"",
      },
      {
        id: 57,
        title: "Perchloroethylene",
        img:"",
        cas:"127-18-4",
        formula:" C2Cl4",
        othernames:"",
      },
      {
        id: 58,
        title: "Phenol",
        img:"",
        cas:"108-95-2",
        formula:"C6H6O or C6H5OH",
        othernames:"",
      },
      {
        id: 59,
        title: "Tertiary Butyl Acetate",
        img:"",
        cas:"540-88-5",
        formula:"C6H12O2",
        othernames:"",
      },
      {
        id: 60,
        title: "Tetrahydrofuran",
        img:"",
        cas:"109-99-9",
        formula:"C4H8O or (CH2)3CH2O",
        othernames:"",
      },
      {
        id: 61,
        title: "Trichloroethylene",
        img:"",
        cas:"79-01-6",
        formula:" C2HCl3",
        othernames:"",
      },

    ];
    export const chemicalsAndIntermediates = [
      {
        id: 1,
        title: " Bromo 3- Chloropropane",
        img:"",
        cas:": 109-70-6",
        formula:": C3H6BrCl ",
        othernames:"",
      },
      {
        id: 2,
        title: "H Triazole",
        img:"",
        cas:"288-88-0",
        formula:"C2H3N3 ",
        othernames:"",
      },
      {
        id: 3,
        title: "Butanediol",
        img:"",
        cas:": 110-63-4",
        formula:"HOCH2CH2CH2CH2OH",
        othernames:"",
      },
      {
        id: 4,
        title: "Dioxane",
        img:"",
        cas:" 123-91-1",
        formula:"C4H4O2",
        othernames:"",
      },
      {
        id: 5,
        title: "Hexanediol",
        img:"",
        cas:"629-11-8",
        formula:"C6H14O2",
        othernames:"",
      },
      {
        id: 6,
        title: "Ethyl Hexanoic acid",
        img:"",
        cas:"149-57-5",
        formula:"CH3(CH2)3CH(C2H5)CO2H",
        othernames:"",
      },
      {
        id: 7,
        title: "Ethyl Hexyl Acrylate",
        img:"",
        cas:"103-11-7",
        formula:"C11H20O2",
        othernames:"",
      },
      {
        id: 8,
        title: "Methyl THF",
        img:"",
        cas:"96-47-9",
        formula:"C5H10O",
        othernames:"",
      },
      {
        id: 9,
        title: "Hydroxy Ethyl Mathacrylate",
        img:"",
        cas:"868-77-9",
        formula:"C6H10O3",
        othernames:"",
      },
      {
        id: 10,
        title: "Di Methoxy Propane",
        img:"",
        cas:"77-76-9 ",
        formula:"C5H12O2",
        othernames:"",
      },
      {
        id: 11,
        title: "Di Methoxy Propane",
        img:"",
        cas:"77-76-9 ",
        formula:"C5H12O2",
        othernames:"",

      },
      {
        id: 12,
        title: "Dichloro Benzyl Chloride",
        img:"",
        cas:"94-99-5",
        formula:"C7H5Cl3",
        othernames:"",

      },
      {
        id: 13,
        title: "Di Methyl Amino Pyridine",
        img:"",
        cas:"1122-58-3",
        formula:"C7H10N2",
        othernames:"",

      },
      {
        id: 14,
        title: "Hydroxy Benzaldehyde",
        img:"",
        cas:"123-08-0",
        formula:"C7H6O2",
        othernames:"",

      },
      {
        id: 15,
        title: "Acetophenone",
        img:"",
        cas:"98-86-2",
        formula:"C6H5C(O)CH3",
        othernames:"",
      },
      {
        id: 16,
        title: "Acrylamide",
        img:"",
        cas:"79-06-1",
        formula:"C3H5NO",
        othernames:"",
      },
      {
        id: 17,
        title: "Acrylic Acid",
        img:"",
        cas:"79-10-7",
        formula:"C3H4O2",
        othernames:"",
      },
      {
        id: 18,
        title: "Adipic Acid",
        img:"",
        cas:"124-04-9",
        formula:"C6H10O4",
        othernames:"",
      },
      {
        id: 19,
        title: "Allyl Alcohol",
        img:"",
        cas:"107-18-6",
        formula:"C3H6O",
        othernames:"",
      },
      {
        id: 20,
        title: "Alpha Naphthol",
        img:"",
        cas:"90-15-3",
        formula:"C10H8O",
        othernames:"",
      },
      {
        id: 21,
        title: "Ammonium Bi Carbonate",
        img:"",
        cas:"1066-33-7",
        formula:"NH4HCO",
        othernames:"",
      },
      {
        id: 22,
        title: "Ammonium Thiocyanate",
        img:"",
        cas:"1762-95-4 ",
        formula:"NH4SCN or CH4N2S",
        othernames:"",
      },
      {
        id: 23,
        title: "Amino Ethylethanolamine",
        img:"",
        cas:"111-41-1",
        formula:"C4H12N2O",
        othernames:"",
      },
      {
        id: 24,
        title: "Amino Guanidine Bicarbonate",
        img:"",
        cas:"2582-30-1",
        formula:"C2H8N4O3",
        othernames:"",
      },
      {
        id: 25,
        title: "Aniline Oil",
        img:"",
        cas:"62-53-3",
        formula:"C6H5NH2",
        othernames:"",
      },
      {
        id: 26,
        title: "Benzoic Acid",
        img:"",
        cas:"65-85-0",
        formula:"C7H6O2 or C6H5COOH",
        othernames:"",
      },
      {
        id: 27,
        title: "Benzophenone",
        img:"",
        cas:"119-61-9",
        formula:"C13H10O or C6H5COC6H5",
        othernames:"",
      },
      {
        id: 28,
        title: "Benzylamine",
        img:"",
        cas:"100-46-9",
        formula:": C7H9N or C6H5CH2NH2",
        othernames:"",
      },
      {
        id: 29,
        title: "Beta Naphthol",
        img:"",
        cas:"135-19-3",
        formula:"C10H8O",
        othernames:"",
      },
      {
        id: 30,
        title: "Bis Trichloro Methyl Carbonate",
        img:"",
        cas:"79-06-1",
        formula:"C3Cl6O",
        othernames:"",
      },
      {
        id: 31,
        title: "Bisphenol A",
        img:"",
        cas:"80-05-7",
        formula:"C15H16O2 or (CH3)2C(C6H4OH)2",
        othernames:"",
      },
      {
        id: 32,
        title: "Caustic Potash Flakes",
        img:"",
        cas:"1310-58-3",
        formula:"KOH",
        othernames:"",
      },
      {
        id: 33,
        title: "Citric Acid Anhydrous",
        img:"",
        cas:"77-92-9",
        formula:"C6H8O7",
        othernames:"",
      },
      {
        id: 34,
        title: "Citric Acid Monohydrate",
        img:"",
        cas:"5949-29-1",
        formula:"C3H4N2O",
        othernames:"",
      },
      {
        id: 35,
        title: "Cyano Acetamide",
        img:"",
        cas:"107-91-5",
        formula:" C3H4N2O",
        othernames:"",
      },
      {
        id: 36,
        title: "Cyclohexane",
        img:"",
        cas:"110-82-7",
        formula:" C6H12",
        othernames:"",
      },
      {
        id: 37,
        title: "Cyclohexanol",
        img:"",
        cas:"108-93-0",
        formula:"C6H12O",
        othernames:"",
      },
      {
        id: 38,
        title: "Cyclohexanone",
        img:"",
        cas:"108-94-1",
        formula:": C6H10O",
        othernames:"",
      },
      {
        id: 39,
        title: "Cyclohexylamine",
        img:"",
        cas:"108-91-8",
        formula:":  C6H13N",
        othernames:"",
      },
      {
        id: 40,
        title: "Cyclopropylamine",
        img:"",
        cas:"765-30-0",
        formula:"C3H7N",
        othernames:"",
      },
      {
        id: 41,
        title: "D- Tartaric Acid",
        img:"",
        cas:"526-83-0",
        formula:"C4H6O6",
        othernames:"",
      },
      {
        id: 42,
        title: "Di Acetone",
        img:"",
        cas:"123-42-2",
        formula:"C6H12O2",
        othernames:"",
      },
      {
        id: 43,
        title: "Di Cyclohexylamine",
        img:"",
        cas:"101-83-7",
        formula:"C12H23N",
        othernames:"",
      },
      {
        id: 44,
        title: "Di Cyclohexylcarbodiimide",
        img:"",
        cas:"538-75-0",
        formula:"C13H22N2",
        othernames:"",
      },
      {
        id: 45,
        title: "Di Ehtyl Ether",
        img:"",
        cas:"60-29-7",
        formula:"C4H10O ",
        othernames:"",
      },
      {
        id: 46,
        title: "Di Ehtyl Sulphate",
        img:"",
        cas:"64-67-5",
        formula:"C4H10O4S or (C2H5)2SO",
        othernames:"",
      },
      {
        id: 47,
        title: "Di Ethylamine",
        img:"",
        cas:"109-89-7",
        formula:"C4H11N",
        othernames:"",
      },
      {
        id: 48,
        title: "Di Ethanolamine",
        img:"",
        cas:"111-42-2",
        formula:"C4H11NO2",
        othernames:"",
      },
      {
        id: 49,
        title: "Di Ethyl Carbonate",
        img:"",
        cas:"105-58-8",
        formula:"C5H10O3 or (C2H5O)2CO",
        othernames:"",
      },
      {
        id: 50,
        title: "Di Ethyl Malonate",
        img:"",
        cas:"105-53-3",
        formula:" C7H12O4",
        othernames:"",
      },
      {
        id: 51,
        title: "Di Ethylene Triamine",
        img:"",
        cas:"1 05-53-3",
        formula:" C4H13N3",
        othernames:"",
      },

      {
        id: 52,
        title: "Di Iso Propyl Ether",
        img:"",
        cas:"108-20-3",
        formula:"C6H14O",
        othernames:"",
      },
     
      {
        id: 53,
        title: "Di Iso Propylamine",
        img:"",
        cas:"108-18-9",
        formula:"C6H15N",
        othernames:"",
      },
      {
        id: 54,
        title: "Di Methyl Amine 40%",
        img:"",
        cas:"124-40-3",
        formula:"(CH3)2NH or C2H7N",
        othernames:"",
      },
      {
        id: 55,
        title: "Di Methyl Carbonate",
        img:"",
        cas:"616-38-6",
        formula:" C3H6O3",
        othernames:"",
      },
      {
        id: 56,
        title: "Di Methyl Malonate",
        img:"",
        cas:"108-59-8",
        formula:"C5H8O",
        othernames:"",
      },
      {
        id: 57,
        title: "Di N Butylamine",
        img:"",
        cas:"111-92-2",
        formula:" C8H19N",
        othernames:"",
      },
      {
        id: 58,
        title: "Di Propylene Glycol",
        img:"",
        cas:"25265-71-8",
        formula:"C6H14O3",
        othernames:"",
      },
      {
        id: 59,
        title: "Di Tret Butyl Dicarbonate",
        img:"",
        cas:"24424-99-5",
        formula:"C10H18O5",
        othernames:"",
      },
      {
        id: 60,
        title: "Dicyandiaminde",
        img:"",
        cas:"461-58-5",
        formula:"C2H4N4",
        othernames:"",
      },
      {
        id: 61,
        title: "Epichlorohydrin",
        img:"",
        cas:"106-89-8",
        formula:"C3H5ClO",
        othernames:"",
      },
      {
        id: 62,
        title: "Epoxy Resin",
        img:"",
        cas:"25068-38-6",
        formula:"C21H25ClO5",
        othernames:"",
      },
      {
        id: 63,
        title: "Ethyl Acetate",
        img:"",
        cas:"141-78-6",
        formula:"C4H8O2 or CH3COOC2H5",
        othernames:"",
      },
      {
        id: 64,
        title: "Ethyl Acetate",
        img:"",
        cas:"141-78-6",
        formula:"C4H8O2 or CH3COOC2H5",
        othernames:"",
      },
      {
        id: 65,
        title: "Ethyl Aceto Acetate",
        img:"",
        cas:"141-97-9",
        formula:"C6H10O3",
        othernames:"",
      },
      {
        id: 66,
        title: "Ethyl Acrylate",
        img:"",
        cas:"140-88-5",
        formula:"C5H8O2",
        othernames:"",
      },
      {
        id: 67,
        title: "Ethyl Chloro Formate",
        img:"",
        cas:"541-41-3",
        formula:"C3H5ClO2 or ClCOOC2H5",
        othernames:"",
      },
      {
        id: 68,
        title: "Ethyl Cyano Acetate",
        img:"",
        cas:"105-56-6",
        formula:"C5H7NO2",
        othernames:"",
      },
      {
        id: 69,
        title: "Ethylene Diamine (EDA)",
        img:"",
        cas:"107-15-3",
        formula:"C2H8N",
        othernames:"",
      },
      {
        id: 70,
        title: "Fluorobenzene",
        img:"",
        cas:"462-06-6",
        formula:"C6H5F",
        othernames:"",
      },
      {
        id: 71,
        title: "Formamide",
        img:"",
        cas:"75-12-7",
        formula:"CH3NO or HCONH2",
        othern1ames:"",
      },
      {
        id: 72,
        title: "Formic Acid 85%",
        img:"",
        cas:"75-12-7",
        formula:"CH3NO or HCONH2",
        othernames:"",
      },
      {
        id: 73,
        title: "Fumaric Acid",
        img:"",
        cas:"110-17-8",
        formula:"C4H4O4",
        othernames:"",
      },
      {
        id: 74,
        title: "Furfuryl Alcohol",
        img:"",
        cas:"98-00-0",
        formula:"C5H6O2",
        othernames:"",
      },
      {
        id: 75,
        title: "Glycerine",
        img:"",
        cas:"56-81-5",
        formula:"C3H8O3",
        othernames:"",
      },
      {
        id: 76,
        title: "Hexamethyldisilazane",
        img:"",
        cas:"999-97-3",
        formula:"C6H19NSi2",
        othernames:"",
      },
      {
        id: 77,
        title: "Hexylene Glycol",
        img:"",
        cas:"107-41-5",
        formula:"C6H14O2",
        othernames:"",
      },
      {
        id: 78,
        title: "Hydrogen Peroxide",
        img:"",
        cas:"7722-84-1",
        formula:"H2O2",
        othernames:"",
      },
      {
        id: 79,
        title: "Hydroquinone",
        img:"",
        cas:"123-31-9",
        formula:"C6H6O2 or C6H4(OH)2",
        othernames:"",
      },
      {
        id: 80,
        title: "Hydroxylamine HCl",
        img:"",
        cas:"5470-11-1",
        formula:"ClH7N2O",
        othernames:"",
      },
      {
        id: 81,
        title: "Hydroxylamine Sulphate",
        img:"",
        cas:"10039-54-0",
        formula:"(NH2OH)2.H2SO4 or H8N2O6S",
        othernames:"",
      },
      {
        id: 82,
        title: "Hexamine",
        img:"",
        cas:"100-97-0",
        formula:"C6H12N4",
        othernames:"",
      },
      {
        id: 83,
        title: "Imidazole",
        img:"",
        cas:"288-32-4",
        formula:"C3H4N2",
        othernames:"",
      },
      {
        id: 84,
        title: "Iodine",
        img:"",
        cas:"7553-56-2",
        formula:"I2",
        othernames:"",
      },
      {
        id: 85,
        title: "Isobutanol",
        img:"",
        cas:"78-83-1",
        formula:"C4H10O or (CH3)2CHCH2OH",
        othernames:"",
      },
      {
        id: 86,
        title: "Iso Butyrlic Acid",
        img:"",
        cas:"79-31-2",
        formula:"C4H8O2",
        othernames:"",
      },
      {
        id: 87,
        title: "Iso Butyrlic Acid",
        img:"",
        cas:"79-31-2",
        formula:"C4H8O2",
        othernames:"",
      },
      {
        id: 88,
        title: "Iso Propyl Alcohol",
        img:"",
        cas:"67-63-0",
        formula:"C3H8O",
        othernames:"",
      },
      {
        id: 89,
        title: "Isopropyl Acetate",
        img:"",
        cas:"108-21-4",
        formula:"C5H10O2",
        othernames:"",
      },
      {
        id: 90,
        title: "Isobutyraldehyde",
        img:"",
        cas:"78-84-2",
        formula:"C4H8O",
        othernames:"",
      },
      {
        id: 91,
        title: "Isophorone",
        img:"",
        cas:"78-59-1",
        formula:"C9H14O",
        othernames:"",
      },
      {
        id: 92,
        title: "Isophorone Diamine",
        img:"",
        cas:"2855-13-2",
        formula:"C10H22N2",
        othernames:"",
      },
      {
        id: 93,
        title: "Isophorone Diamine",
        img:"",
        cas:"2855-13-2",
        formula:"C10H22N2",
        othernames:"",
      },
      {
        id: 94,
        title: "Isophthalic Acid",
        img:"",
        cas:"121-91-5",
        formula:" C8H6O4",
        othernames:"",
      },
      {
        id: 95,
        title: "Isovaleraldehyde",
        img:"",
        cas:"590-86-3",
        formula:" C5H10O",
        othernames:"",
      },
      {
        id: 96,
        title: "L - Tartaric Acid",
        img:"",
        cas:"526-83-0",
        formula:"C4H6O6",
        othernames:"",
      },
      {
        id: 97,
        title: "Lactose",
        img:"",
        cas:"63-42-3",
        formula:" C12H22O11",
        othernames:"",
      },
      {
        id: 98,
        title: "Lithium Carbonate",
        img:"",
        cas:"554-13-2",
        formula:"Li2CO3 or CLi2O3",
        othernames:"",
      },
      {
        id: 99,
        title: "Lithium Hydroxide",
        img:"",
        cas:"1310-65-2",
        formula:"LiOH or HLiO",
        othernames:"",
      },
      {
        id: 100,
        title: "Maliec Anhydride",
        img:"",
        cas:"108-31-6",
        formula:"C4H2O3",
        othernames:"",
      },
      {
        id: 101,
        title: "Malonic Acid",
        img:"",
        cas:"141-82-2",
        formula:"C3H4O4",
        othernames:"",
      },
      {
        id: 102,
        title: "Malononitrile",
        img:"",
        cas:"109-77-3",
        formula:"C3H2N2 or NCCH2CN or CH2(CN)2",
        othernames:"",
      },
      {
        id: 103,
        title: "Melamine",
        img:"",
        cas:"108-78-1",
        formula:"C3H6N6 or C3N3(NH2)3",
        othernames:"",
      },
      {
        id: 104,
        title: "Meta Cresol",
        img:"",
        cas:"108-39-4",
        formula:"C7H8O or CH3C6H4OH",
        othernames:"",
      },
      {
        id: 105,
        title: "Metha Acrylic Acid",
        img:"",
        cas:"79-41-4",
        formula:"C4H6O2",
        othernames:"",
      },
      {
        id: 106,
        title: "Methane Sulphonic Acid",
        img:"",
        cas:"75-75-2",
        formula:"CH4O3S",
        othernames:"",
      },
      {
        id: 107,
        title: "Methane Sulphonyl Chloride",
        img:"",
        cas:"124-63-0",
        formula:"CH3ClO2S",
        othernames:"",
      },
      {
        id: 108,
        title: "Methyl Aceto Acetate",
        img:"",
        cas:"105-45-3",
        formula:"C5H8O3",
        othernames:"",
      },
      {
        id: 109,
        title: "Methyl Chloro Formate",
        img:"",
        cas:"79-22-1",
        formula:"C2H3ClO2 or CH3OCOCl",
        othernames:"",
      },
      {
        id: 110,
        title: "Methyl Cyano Acetate",
        img:"",
        cas:"105-34-0",
        formula:"C4H5NO2",
        othernames:"",
      },
      {
        id: 111,
        title: "Methyl Cyclohexane",
        img:"",
        cas:"101-68-8",
        formula:"C15H10N2O2",
        othernames:"",
      },
      {
        id: 112,
        title: "Methylene Diphenyl Diisocyante",
        img:"",
        cas:"108-87-2",
        formula:"C7H14 or C6H11CH3",
        othernames:"",
      },
      {
        id: 113,
        title: "Methyl Methacrylate",
        img:"",
        cas:"80-62-6",
        formula:"C5H8O2",
        othernames:"",
      },
      {
        id: 114,
        title: "Monoethylamine",
        img:"",
        cas:"75-04-7",
        formula:"CH3CH2NH2",
        othernames:"",
      },
      {
        id: 115,
        title: "Mono Chloro Benzene",
        img:"",
        cas:"108-90-7",
        formula:"C6H5Cl",
        othernames:"",
      },
      {
        id: 116,
        title: "Mono Methylamine",
        img:"",
        cas:"74-89-5",
        formula:"CH5N or CH3NH2",
        othernames:"",
      },
      {
        id: 117,
        title: "Mono Ethylene Glycol",
        img:"",
        cas:"107-21-1",
        formula:"C2H6O2",
        othernames:"",
      },
      {
        id: 118,
        title: "Mono Iso Propylamine 70%",
        cas:"75-31-0",
        formula:"C3H9N or (CH3)2CHNH2",
        othernames:"",
      },
      {
        id: 119,
        title: "Mono Iso Propylamine 99%",
        img:"",
        cas:"75-31-0",
        formula:"C3H9N or (CH3)2CHNH2",
        othernames:"",
      },
      {
        id: 120,
        title: "Morpholine",
        img:"",
        cas:"110-91-8",
        formula:"C4H9NO",
        othernames:"",
      },
      {
        id: 121,
        title: "MP Diol Glycol",
        img:"",
        cas:"2163-42-0",
        formula:"C4H10O2",
        othernames:"",
      },
      {
        id: 122,
        title: "N- Ethyl Piperazine",
        img:"",
        cas:"5308-25-8",
        formula:"C6H14N2",
        othernames:"",
      },
      {
        id: 123,
        title: "N- Butyric Acid",
        img:"",
        cas:"107-92-6",
        formula:"C4H8O2",
        othernames:"",
      },
      {
        id: 124,
        title: "N- Butyl Methacrylate",
        img:"",
        cas:"97-88-1",
        formula:"C8H14O2",
        othernames:"",
      },
      {
        id: 125,
        title: "N- Butanol",
        img:"",
        cas:"71-36-3",
        formula:"C4H10O",
        othernames:"",
      },
      {
        id: 126,
        title: "N- Butyraldehyde",
        img:"",
        cas:"123-72-8",
        formula:"C4H8O",
        othernames:"",
      },
      {
        id: 127,
        title: "N- Methyl Piperazine",
        img:"",
        cas:"109-01-3",
        formula:"C5H12N2",
        othernames:"",
      },
      {
        id: 128,
        title: "Napthalene Crude",
        img:"",
        cas:"91-20-3",
        formula:"C10H8",
        othernames:"",
      },
      {
        id: 129,
        title: "Napthalene Refined",
        img:"",
        cas:"91-20-3",
        formula:"C10H8",
        othernames:"",
      },
      {
        id: 130,
        title: "Neo Pentyl Glycol",
        img:"",
        cas:"126-30-7",
        formula:"C5H12O2",
        othernames:"",
      },
      {
        id: 131,
        title: "Nitromethane",
        img:"",
        cas:"75-52-5",
        formula:"CH3NO2",
        othernames:"",
      },
      {
        id: 132,
        title: "Nonyl Phenol",
        img:"",
        cas:"104-40-5",
        formula:"C15H24O",
        othernames:"",
      },
      {
        id: 133,
        title: "Nonyl Phenol Ethoxylate",
        img:"",
        cas:"20427-84-3",
        formula:"C19H32O3",
        othernames:"",
      },
      {
        id: 134,
        title: "Oxone PS - 16",
        img:"",
        cas:"37222-66-5",
        formula:" H3K5O18S4",
        othernames:"",
      },
      {
        id: 135,
        title: "Para Tertiary Butyl Phenol",
        img:"",
        cas:"98-54-4",
        formula:"C10H14O or HOC6H4C(CH3)3",
        othernames:"",
      },
      {
        id: 136,
        title: "Para Tertiary Octyl Phenol",
        img:"",
        cas:"140-66-9",
        formula:"C14H22O",
        othernames:"",
      },
      {
        id: 137,
        title: "Para Toluene Sulfonyl Chloride",
        img:"",
        cas:"98-59-9",
        formula:"C7H7ClO2S",
        othernames:"",
      },
      {
        id: 138,
        title: "Paraformaldehyde 91%",
        img:"",
        cas:"30525-89-4",
        formula:"(CH2O)n",
        othernames:"",
      },
      {
        id: 139,
        title: "Paraformaldehyde 96%",
        img:"",
        cas:"30525-89-4",
        formula:"(CH2O)n",
        othernames:"",
      },
      {
        id: 140,
        title: "Pentaerythritol 98%",
        img:"",
        cas:"30525-89-4",
        formula:"(CH2O)n",
        othernames:"",
      },
      {
        id: 141,
        title: "Perchloroethylene",
        img:"",
        cas:"127-18-4",
        formula:" C2Cl4",
        othernames:"",
      },
      {
        id: 142,
        title: "Phosphoric Acid (Food Grade)",
        img:"",
        cas:"7664-38-2",
        formula:"H3PO4 or H3O4P",
        othernames:"",
      },
      {
        id: 143,
        title: "Phosphoric Acid (Technical)",
        img:"",
        cas:"7664-38-2",
        formula:" H3PO4 or H3O4P",
        othernames:"",
      },
      {
        id: 144,
        title: "Phosphorus Oxychloride",
        img:"",
        cas:"10025-87-3",
        formula:" POCl3",
        othernames:"",
      },
      {
        id: 145,
        title: "Phosphorus Pentaoxide",
        img:"",
        cas:"1314-56-3",
        formula:"P4O10 or P2O",
        othernames:"",
      },
      {
        id: 146,
        title: "Piperazine Anhydrous",
        img:"",
        cas:"110-85-0",
        formula:"C4H10N2",
        othernames:"",
      },
      {
        id: 147,
        title: "Poly Vinyl Alcohol",
        img:"",
        cas:"9002-89-5",
        formula:"C2H4O",
        othernames:"",
      },
      {
        id: 148,
        title: "Poly Vinyl Alcohol",
        img:"",
        cas:"25322-68-3",
        formula:"C69H140O35",
        othernames:"",
      },
      {
        id: 149,
        title: "Polypropylene Glycol 1000D",
        img:"",
        cas:"25322-69-4",
        formula:"C6H14O3",
        othernames:"",
      },
      {
        id: 150,
        title: "Polypropylene Glycol 2000D",
        img:"",
        cas:"25322-69-4",
        formula:"C6H14O3",
        othernames:"",
      },
      {
        id: 151,
        title: "Potassium Bi Carbonate",
        img:"",
        cas:"298-14-6",
        formula:"KHCO3",
        othernames:"",
      },
      {
        id: 152,
        title: "Potassium Carbonate (Granual)",
        img:"",
        cas:"584-08-7",
        formula:"K2CO3",
        othernames:"",
      },
      {
        id: 152,
        title: "Potassium Carbonate (Powder)",
        img:"",
        cas:"584-08-7 ",
        formula:" K2CO3",
        othernames:"",
      },  
      {
        id: 153,
        title: "Potassium Permanganate",
        img:"",
        cas:"7722-64-7",
        formula:" K2CO3",
        othernames:"",
      },  
      {
        id: 154,
        title: "Phenyl Chloro Formate",
        img:"",
        cas:"1885-14-9",
        formula:"C7H5ClO2 or C6H5OCOCl",
        othernames:"",
      },
      {
        id: 155,
        title: "Propionaldehyde",
        img:"",
        cas:"123-38-6",
        formula:"C3H6O or CH3CH2CHO8",
        othernames:"",
      },
      {
        id: 156,
        title: "Propionic Acid",
        img:"",
        cas:"79-09-4",
        formula:"C3H6O2",
        othernames:"",
      },
      {
        id: 157,
        title: "Propionic Anhydride",
        img:"",
        cas:"123-62-6",
        formula:" C6H10O3 or (CH3CH2CO)2O",
        othernames:"",
      },
      {
        id: 158,
        title: "Propargyl Alcohol",
        img:"",
        cas:"107-19-7",
        formula:"C3H4O or CHCCH2OH",
        othernames:"",
      },
      {
        id: 159,
        title: "Propylene Glycol (Technical)",
        img:"",
        cas:"57-55-6",
        formula:"C3H8O2",
        othernames:"",
      },
      {
        id: 160,
        title: "Propylene Glycol (USP)",
        img:"",
        cas:"57-55-6",
        formula:"C3H8O2",
        othernames:"",
      },
      {
        id: 161,
        title: "Phthalic Anhydride",
        img:"",
        cas:"85-44-9",
        formula:"C8H4O3 or C6H4(CO)2O",
        othernames:"",
      },
      {
        id: 162,
        title: "Pyridine",
        img:"",
        cas:"110-86-1",
        formula:" C5H5N",
        othernames:"",
      },
      
      {
        id: 163,
        title: "Pyridine",
        img:"",
        cas:"123-75-1",
        formula:"C4H9N",
        othernames:"",
      },
      
      {
        id: 163,
        title: "Resorcinol",
        img:"",
        cas:"108-46-3",
        formula:"C6H6O2",
        othernames:"",
      },
      {
        id: 163,
        title: "Soda Ash",
        img:"",
        cas:"497-19-8",
        formula:"Na2CO3",
        othernames:"",
      },
      {
        id: 164,
        title: "Sodium Borohydride (Granual)",
        img:"",
        cas:"16940-66-2",
        formula:"NaBH4 or BH4Na",
        othernames:"",
      },
      
      {
        id: 165,
        title: "Sodium Borohydride (Powder)",
        img:"",
        cas:"16940-66-2",
        formula:" NaBH4 or BH4Na",
        othernames:"",
      },
      {
        id: 166,
        title: "Sodium Cyanide",
        img:"",
        cas:"143-33-9",
        formula:"NaCN or CNNa",
        othernames:"",
      },
      {
        id: 167,
        title: "Sodium Gluconate",
        img:"",
        cas:"527-07-1",
        formula:" C6H11NaO7",
        othernames:"",
      },
      {
        id: 168,
        title: "Sodium Gluconate",
        img:"",
        cas:"527-07-1",
        formula:"C6H11NaO7",
        othernames:"",
      },
      {
        id: 169,
        title: "Sodium Ligno Sulphonate",
        img:"",
        cas:"8061-51-6",
        formula:" C20H24Na2O10S2",
        othernames:"",
      },
      {
        id: 170,
        title: "Sodium Metabisulphite",
        img:"",
        cas:"7681-57-4",
        formula:" Na2S2O5",
        othernames:"",
      },
      {
        id: 171,
        title: "Sodium Metal",
        img:"",
        cas:"7440-23-5",
        formula:"Na",
        othernames:"",
      },
      {
        id: 172,
        title: "Sodium Methoxide Powder",
        img:"",
        cas:"124-41-4",
        formula:"CH3ONa or CH3NaO",
        othernames:"",
      },
      {
        id: 173,
        title: "Sodium Nitrate",
        img:"",
        cas:"7631-99-4",
        formula:" NaNO3 or NNaO3",
        othernames:"",
      },
      {
        id: 174,
        title: "Sodium Nitrite",
        img:"",
        cas:"7632-00-0",
        formula:" NaNO2 or NNaO2",
        othernames:"",
      },
      
      {
        id: 175,
        title: "Sodium Thiocyanate",
        img:"",
        cas:"540-72-7",
        formula:"NaSCN or CNNaS",
        othernames:"",
      },
      {
        id: 176,
        title: "Sodium Tri Polyphosphate",
        img:"",
        cas:"7758-29-4",
        formula:"Na5O10P3",
        othernames:"",
      },
      {
        id: 176,
        title: "Tertiary Butanol",
        img:"",
        cas:"75-65-0",
        formula:":C4H10O or (CH3)3COH",
        othernames:"",
      },
      
      {
        id: 177,
        title: "Tertiary Butylamine",
        img:"",
        cas:"75-64-9",
        formula:":C4H10O or (CH3)3COH",
        othernames:"",
      },
      {
        id: 177,
        title: "Tertiary Butylamine",
        img:"",
        cas:"75-64-9",
        formula:"C4H10O or (CH3)3COH",
        othernames:"",
      },
      {
        id: 178,
        title: "Thiophenol",
        img:"",
        cas:"108-98-5",
        formula:"C6H6S or C6H5SH",
        othernames:"",
      },
      {
        id: 179,
        title: "Thiourea",
        img:"",
        cas:"62-56-6",
        formula:" CH4N2S or H2NCSNH2",
        othernames:"",
      },
      
      {
        id: 180,
        title: "Toluene Di Isocyanate",
        img:"",
        cas:"584-84-9",
        formula:"C9H6N2O2 or CH3C6H3(NCO)2",
        othernames:"",
      },
      
      {
        id: 181,
        title: "Tri Ethyl Phosphate",
        img:"",
        cas:"78-40-0",
        formula:"C6H15O4P or (C2H5)3PO4",
        othernames:"",
      },
      
      {
        id: 182,
        title: "Tri Ethyl Amine",
        img:"",
        cas:"121-44-8",
        formula:"C6H15N or (C2H5)3N",
        othernames:"",
      },
      {
        id: 183,
        title: "Tri Ethylene Pentamine",
        img:"",
        cas:"112-57-2",
        formula:": C8H23N5",
        othernames:"",
      },
      {
        id: 184,
        title: "Tri Mellitic Anhydride",
        img:"",
        cas:"552-30-7",
        formula:" C9H4O5",
        othernames:"",
      },
      {
        id: 185,
        title: "Tri Methyl Ortho Acetate",
        img:"",
        cas:"1445-45-0 ",
        formula:"C5H12O3",
        othernames:"",
      },
      {
        id: 186,
        title: "Tri Methyl Ortho Formate",
        img:"",
        cas:"112-57-2 ",
        formula:"C8H23N5",
        othernames:"",
      },
      
      {
        id: 187,
        title: "Tri Methylol Propane",
        img:"",
        cas:"112-57-2 ",
        formula:"C8H23N5",
        othernames:"",
      },
      
      {
        id: 188,
        title: "Tri N Butylamine",
        img:"",
        cas:"102-82-9 ",
        formula:"C12H27N",
        othernames:"",
      },
      {
        id: 189,
        title: "Triethanolamine 85% & 99%",
        img:"",
        cas:"102-71-6 ",
        formula:"C6H15NO3",
        othernames:"",
      },
      {
        id: 190,
        title: "Triethylene Tetramine",
        img:"",
        cas:"112-24-3",
        formula:"C6H18N4",
        othernames:"",
      },
      
      {
        id: 191,
        title: "Urea (Technical Grade)",
        img:"",
        cas:"57-13-6 ",
        formula:"CH4N2O or NH2CONH2",
        othernames:"",
      },
      
      
    ];
    export const specialityChemicals = [
      {
        id: 1,
        title: "Di Methyl Amino Pyridine",
        img:"",
        cas:"1122-58-3",
        formula:"C7H10N2",
        othernames:"",
      },
      {
        id: 2,
        title: "Piperidine",
        img:"",
        cas:"110-89-4",
        formula:" C5H11N",
        othernames:"",
      },
    ];
  